const ANSWERS = [
  // North America - USA
  {code: "ATL", name: "Hartsfield-Jackson Atlanta International Airport", city: "Atlanta, USA"},
  {code: "LAX", name: "Los Angeles International Airport", city: "Los Angeles, USA"},
  {code: "ORD", name: "O'Hare International Airport", city: "Chicago, USA"},
  {code: "DFW", name: "Dallas/Fort Worth International Airport", city: "Dallas, USA"},
  {code: "DEN", name: "Denver International Airport", city: "Denver, USA"},
  {code: "JFK", name: "John F. Kennedy International Airport", city: "New York, USA"},
  {code: "SFO", name: "San Francisco International Airport", city: "San Francisco, USA"},
  {code: "SEA", name: "Seattle-Tacoma International Airport", city: "Seattle, USA"},
  {code: "LAS", name: "Harry Reid International Airport", city: "Las Vegas, USA"},
  {code: "MCO", name: "Orlando International Airport", city: "Orlando, USA"},
  {code: "EWR", name: "Newark Liberty International Airport", city: "Newark, USA"},
  {code: "MIA", name: "Miami International Airport", city: "Miami, USA"},
  {code: "PHX", name: "Phoenix Sky Harbor International Airport", city: "Phoenix, USA"},
  {code: "IAH", name: "George Bush Intercontinental Airport", city: "Houston, USA"},
  {code: "BOS", name: "Boston Logan International Airport", city: "Boston, USA"},
  {code: "MSP", name: "Minneapolis-Saint Paul International Airport", city: "Minneapolis, USA"},
  {code: "DTW", name: "Detroit Metropolitan Airport", city: "Detroit, USA"},
  {code: "PHL", name: "Philadelphia International Airport", city: "Philadelphia, USA"},
  {code: "LGA", name: "LaGuardia Airport", city: "New York, USA"},
  {code: "BWI", name: "Baltimore/Washington International Airport", city: "Baltimore, USA"},
  {code: "SLC", name: "Salt Lake City International Airport", city: "Salt Lake City, USA"},
  {code: "DCA", name: "Ronald Reagan Washington National Airport", city: "Washington, USA"},
  {code: "IAD", name: "Washington Dulles International Airport", city: "Washington, USA"},
  {code: "SAN", name: "San Diego International Airport", city: "San Diego, USA"},
  {code: "TPA", name: "Tampa International Airport", city: "Tampa, USA"},
  {code: "PDX", name: "Portland International Airport", city: "Portland, USA"},
  {code: "HNL", name: "Daniel K. Inouye International Airport", city: "Honolulu, USA"},
  {code: "STL", name: "St. Louis Lambert International Airport", city: "St. Louis, USA"},
  {code: "AUS", name: "Austin-Bergstrom International Airport", city: "Austin, USA"},
  {code: "BNA", name: "Nashville International Airport", city: "Nashville, USA"},
  {code: "MSY", name: "Louis Armstrong New Orleans International Airport", city: "New Orleans, USA"},
  {code: "RDU", name: "Raleigh-Durham International Airport", city: "Raleigh, USA"},
  {code: "SJC", name: "San Jose International Airport", city: "San Jose, USA"},
  {code: "SMF", name: "Sacramento International Airport", city: "Sacramento, USA"},
  {code: "CLE", name: "Cleveland Hopkins International Airport", city: "Cleveland, USA"},
  {code: "OAK", name: "Oakland International Airport", city: "Oakland, USA"},
  {code: "PIT", name: "Pittsburgh International Airport", city: "Pittsburgh, USA"},
  {code: "IND", name: "Indianapolis International Airport", city: "Indianapolis, USA"},
  {code: "CMH", name: "John Glenn Columbus International Airport", city: "Columbus, USA"},
  {code: "JAX", name: "Jacksonville International Airport", city: "Jacksonville, USA"},
  {code: "ANC", name: "Ted Stevens Anchorage International Airport", city: "Anchorage, USA"},
  {code: "OGG", name: "Kahului Airport", city: "Maui, USA"},
  {code: "HOU", name: "William P. Hobby Airport", city: "Houston, USA"},
  {code: "MKE", name: "Milwaukee Mitchell International Airport", city: "Milwaukee, USA"},
  {code: "RNO", name: "Reno-Tahoe International Airport", city: "Reno, USA"},
  {code: "ABQ", name: "Albuquerque International Sunport", city: "Albuquerque, USA"},
  {code: "BUF", name: "Buffalo Niagara International Airport", city: "Buffalo, USA"},
  {code: "MCI", name: "Kansas City International Airport", city: "Kansas City, USA"},
  {code: "FLL", name: "Fort Lauderdale-Hollywood International Airport", city: "Fort Lauderdale, USA"},
  {code: "CLT", name: "Charlotte Douglas International Airport", city: "Charlotte, USA"},
  // North America - Canada
  {code: "YYZ", name: "Toronto Pearson International Airport", city: "Toronto, Canada"},
  {code: "YVR", name: "Vancouver International Airport", city: "Vancouver, Canada"},
  {code: "YUL", name: "Montréal-Trudeau International Airport", city: "Montreal, Canada"},
  {code: "YYC", name: "Calgary International Airport", city: "Calgary, Canada"},
  {code: "YOW", name: "Ottawa Macdonald-Cartier International Airport", city: "Ottawa, Canada"},
  {code: "YEG", name: "Edmonton International Airport", city: "Edmonton, Canada"},
  {code: "YHZ", name: "Halifax Stanfield International Airport", city: "Halifax, Canada"},
  {code: "YWG", name: "Winnipeg James Armstrong Richardson International Airport", city: "Winnipeg, Canada"},
  // North America - Mexico & Caribbean
  {code: "MEX", name: "Mexico City International Airport", city: "Mexico City, Mexico"},
  {code: "CUN", name: "Cancún International Airport", city: "Cancún, Mexico"},
  {code: "GDL", name: "Guadalajara International Airport", city: "Guadalajara, Mexico"},
  {code: "SJD", name: "Los Cabos International Airport", city: "San Jose del Cabo, Mexico"},
  {code: "PVR", name: "Licenciado Gustavo Díaz Ordaz International Airport", city: "Puerto Vallarta, Mexico"},
  {code: "MBJ", name: "Sangster International Airport", city: "Montego Bay, Jamaica"},
  {code: "NAS", name: "Lynden Pindling International Airport", city: "Nassau, Bahamas"},
  {code: "SJU", name: "Luis Muñoz Marín International Airport", city: "San Juan, Puerto Rico"},
  {code: "PUJ", name: "Punta Cana International Airport", city: "Punta Cana, Dominican Republic"},
  {code: "SDQ", name: "Las Américas International Airport", city: "Santo Domingo, Dominican Republic"},
  {code: "HAV", name: "José Martí International Airport", city: "Havana, Cuba"},
  // South America
  {code: "GRU", name: "São Paulo/Guarulhos International Airport", city: "São Paulo, Brazil"},
  {code: "GIG", name: "Rio de Janeiro/Galeão International Airport", city: "Rio de Janeiro, Brazil"},
  {code: "EZE", name: "Ministro Pistarini International Airport", city: "Buenos Aires, Argentina"},
  {code: "SCL", name: "Arturo Merino Benítez International Airport", city: "Santiago, Chile"},
  {code: "BOG", name: "El Dorado International Airport", city: "Bogotá, Colombia"},
  {code: "LIM", name: "Jorge Chávez International Airport", city: "Lima, Peru"},
  {code: "UIO", name: "Mariscal Sucre International Airport", city: "Quito, Ecuador"},
  {code: "CCS", name: "Simón Bolívar International Airport", city: "Caracas, Venezuela"},
  {code: "MVD", name: "Carrasco International Airport", city: "Montevideo, Uruguay"},
  {code: "PTY", name: "Tocumen International Airport", city: "Panama City, Panama"},
  {code: "SJO", name: "Juan Santamaría International Airport", city: "San Jose, Costa Rica"},
  {code: "CTG", name: "Rafael Núñez International Airport", city: "Cartagena, Colombia"},
  {code: "MDE", name: "José María Córdova International Airport", city: "Medellín, Colombia"},
  {code: "CUZ", name: "Alejandro Velasco Astete International Airport", city: "Cusco, Peru"},
  // Europe - United Kingdom & Ireland
  {code: "LHR", name: "London Heathrow Airport", city: "London, UK"},
  {code: "LGW", name: "London Gatwick Airport", city: "London, UK"},
  {code: "STN", name: "London Stansted Airport", city: "London, UK"},
  {code: "LTN", name: "London Luton Airport", city: "London, UK"},
  {code: "MAN", name: "Manchester Airport", city: "Manchester, UK"},
  {code: "EDI", name: "Edinburgh Airport", city: "Edinburgh, UK"},
  {code: "BHX", name: "Birmingham Airport", city: "Birmingham, UK"},
  {code: "GLA", name: "Glasgow Airport", city: "Glasgow, UK"},
  {code: "BRS", name: "Bristol Airport", city: "Bristol, UK"},
  {code: "DUB", name: "Dublin Airport", city: "Dublin, Ireland"},
  {code: "SNN", name: "Shannon Airport", city: "Shannon, Ireland"},
  // Europe - Western
  {code: "CDG", name: "Charles de Gaulle Airport", city: "Paris, France"},
  {code: "ORY", name: "Paris Orly Airport", city: "Paris, France"},
  {code: "NCE", name: "Nice Côte d'Azur Airport", city: "Nice, France"},
  {code: "LYS", name: "Lyon-Saint Exupéry Airport", city: "Lyon, France"},
  {code: "MRS", name: "Marseille Provence Airport", city: "Marseille, France"},
  {code: "AMS", name: "Amsterdam Schiphol Airport", city: "Amsterdam, Netherlands"},
  {code: "BRU", name: "Brussels Airport", city: "Brussels, Belgium"},
  {code: "FRA", name: "Frankfurt Airport", city: "Frankfurt, Germany"},
  {code: "MUC", name: "Munich Airport", city: "Munich, Germany"},
  {code: "TXL", name: "Berlin Tegel Airport", city: "Berlin, Germany"},
  {code: "BER", name: "Berlin Brandenburg Airport", city: "Berlin, Germany"},
  {code: "HAM", name: "Hamburg Airport", city: "Hamburg, Germany"},
  {code: "DUS", name: "Düsseldorf Airport", city: "Düsseldorf, Germany"},
  {code: "CGN", name: "Cologne Bonn Airport", city: "Cologne, Germany"},
  {code: "STR", name: "Stuttgart Airport", city: "Stuttgart, Germany"},
  {code: "ZRH", name: "Zürich Airport", city: "Zürich, Switzerland"},
  {code: "GVA", name: "Geneva Airport", city: "Geneva, Switzerland"},
  {code: "VIE", name: "Vienna International Airport", city: "Vienna, Austria"},
  {code: "LUX", name: "Luxembourg Airport", city: "Luxembourg, Luxembourg"},
  // Europe - Southern
  {code: "FCO", name: "Leonardo da Vinci–Fiumicino Airport", city: "Rome, Italy"},
  {code: "MXP", name: "Milan Malpensa Airport", city: "Milan, Italy"},
  {code: "VCE", name: "Venice Marco Polo Airport", city: "Venice, Italy"},
  {code: "NAP", name: "Naples International Airport", city: "Naples, Italy"},
  {code: "FLR", name: "Florence Airport", city: "Florence, Italy"},
  {code: "MAD", name: "Adolfo Suárez Madrid-Barajas Airport", city: "Madrid, Spain"},
  {code: "BCN", name: "Barcelona-El Prat Airport", city: "Barcelona, Spain"},
  {code: "AGP", name: "Málaga Airport", city: "Málaga, Spain"},
  {code: "PMI", name: "Palma de Mallorca Airport", city: "Palma de Mallorca, Spain"},
  {code: "IBZ", name: "Ibiza Airport", city: "Ibiza, Spain"},
  {code: "TFS", name: "Tenerife South Airport", city: "Tenerife, Spain"},
  {code: "LIS", name: "Lisbon Humberto Delgado Airport", city: "Lisbon, Portugal"},
  {code: "OPO", name: "Porto Airport", city: "Porto, Portugal"},
  {code: "FAO", name: "Faro Airport", city: "Faro, Portugal"},
  {code: "ATH", name: "Athens International Airport", city: "Athens, Greece"},
  {code: "SKG", name: "Thessaloniki Airport", city: "Thessaloniki, Greece"},
  {code: "JTR", name: "Santorini Airport", city: "Santorini, Greece"},
  {code: "JMK", name: "Mykonos Airport", city: "Mykonos, Greece"},
  {code: "HER", name: "Heraklion Airport", city: "Heraklion, Greece"},
  {code: "MLA", name: "Malta International Airport", city: "Valletta, Malta"},
  // Europe - Scandinavia
  {code: "CPH", name: "Copenhagen Airport", city: "Copenhagen, Denmark"},
  {code: "ARN", name: "Stockholm Arlanda Airport", city: "Stockholm, Sweden"},
  {code: "OSL", name: "Oslo Gardermoen Airport", city: "Oslo, Norway"},
  {code: "HEL", name: "Helsinki-Vantaa Airport", city: "Helsinki, Finland"},
  {code: "KEF", name: "Keflavík International Airport", city: "Reykjavik, Iceland"},
  {code: "GOT", name: "Göteborg Landvetter Airport", city: "Gothenburg, Sweden"},
  {code: "BGO", name: "Bergen Airport", city: "Bergen, Norway"},
  // Europe - Eastern
  {code: "WAW", name: "Warsaw Chopin Airport", city: "Warsaw, Poland"},
  {code: "KRK", name: "Kraków John Paul II International Airport", city: "Kraków, Poland"},
  {code: "PRG", name: "Václav Havel Airport Prague", city: "Prague, Czech Republic"},
  {code: "BUD", name: "Budapest Ferenc Liszt International Airport", city: "Budapest, Hungary"},
  {code: "OTP", name: "Henri Coandă International Airport", city: "Bucharest, Romania"},
  {code: "SOF", name: "Sofia Airport", city: "Sofia, Bulgaria"},
  {code: "ZAG", name: "Zagreb Airport", city: "Zagreb, Croatia"},
  {code: "DBV", name: "Dubrovnik Airport", city: "Dubrovnik, Croatia"},
  {code: "SPU", name: "Split Airport", city: "Split, Croatia"},
  {code: "BEG", name: "Belgrade Nikola Tesla Airport", city: "Belgrade, Serbia"},
  {code: "LJU", name: "Ljubljana Jože Pučnik Airport", city: "Ljubljana, Slovenia"},
  {code: "TLL", name: "Tallinn Airport", city: "Tallinn, Estonia"},
  {code: "RIX", name: "Riga International Airport", city: "Riga, Latvia"},
  {code: "VNO", name: "Vilnius Airport", city: "Vilnius, Lithuania"},
  // Europe - Russia & Turkey
  {code: "SVO", name: "Sheremetyevo International Airport", city: "Moscow, Russia"},
  {code: "DME", name: "Domodedovo International Airport", city: "Moscow, Russia"},
  {code: "LED", name: "Pulkovo Airport", city: "Saint Petersburg, Russia"},
  {code: "IST", name: "Istanbul Airport", city: "Istanbul, Turkey"},
  {code: "SAW", name: "Sabiha Gökçen International Airport", city: "Istanbul, Turkey"},
  {code: "AYT", name: "Antalya Airport", city: "Antalya, Turkey"},
  {code: "ADB", name: "Izmir Adnan Menderes Airport", city: "Izmir, Turkey"},
  // Middle East
  {code: "DXB", name: "Dubai International Airport", city: "Dubai, UAE"},
  {code: "AUH", name: "Abu Dhabi International Airport", city: "Abu Dhabi, UAE"},
  {code: "DOH", name: "Hamad International Airport", city: "Doha, Qatar"},
  {code: "RUH", name: "King Khalid International Airport", city: "Riyadh, Saudi Arabia"},
  {code: "JED", name: "King Abdulaziz International Airport", city: "Jeddah, Saudi Arabia"},
  {code: "TLV", name: "Ben Gurion Airport", city: "Tel Aviv, Israel"},
  {code: "AMM", name: "Queen Alia International Airport", city: "Amman, Jordan"},
  {code: "BAH", name: "Bahrain International Airport", city: "Manama, Bahrain"},
  {code: "MCT", name: "Muscat International Airport", city: "Muscat, Oman"},
  {code: "KWI", name: "Kuwait International Airport", city: "Kuwait City, Kuwait"},
  {code: "BEY", name: "Rafic Hariri International Airport", city: "Beirut, Lebanon"},
  // Africa
  {code: "JNB", name: "O.R. Tambo International Airport", city: "Johannesburg, South Africa"},
  {code: "CPT", name: "Cape Town International Airport", city: "Cape Town, South Africa"},
  {code: "CAI", name: "Cairo International Airport", city: "Cairo, Egypt"},
  {code: "HRG", name: "Hurghada International Airport", city: "Hurghada, Egypt"},
  {code: "SSH", name: "Sharm El Sheikh International Airport", city: "Sharm El Sheikh, Egypt"},
  {code: "CMN", name: "Mohammed V International Airport", city: "Casablanca, Morocco"},
  {code: "RAK", name: "Marrakech Menara Airport", city: "Marrakech, Morocco"},
  {code: "NBO", name: "Jomo Kenyatta International Airport", city: "Nairobi, Kenya"},
  {code: "ADD", name: "Addis Ababa Bole International Airport", city: "Addis Ababa, Ethiopia"},
  {code: "LOS", name: "Murtala Muhammed International Airport", city: "Lagos, Nigeria"},
  {code: "ABJ", name: "Félix-Houphouët-Boigny International Airport", city: "Abidjan, Ivory Coast"},
  {code: "ACC", name: "Kotoka International Airport", city: "Accra, Ghana"},
  {code: "DAR", name: "Julius Nyerere International Airport", city: "Dar es Salaam, Tanzania"},
  {code: "DSS", name: "Blaise Diagne International Airport", city: "Dakar, Senegal"},
  {code: "TUN", name: "Tunis-Carthage International Airport", city: "Tunis, Tunisia"},
  {code: "ALG", name: "Houari Boumediene Airport", city: "Algiers, Algeria"},
  {code: "ZNZ", name: "Abeid Amani Karume International Airport", city: "Zanzibar, Tanzania"},
  // Asia - East
  {code: "NRT", name: "Narita International Airport", city: "Tokyo, Japan"},
  {code: "HND", name: "Tokyo Haneda Airport", city: "Tokyo, Japan"},
  {code: "KIX", name: "Kansai International Airport", city: "Osaka, Japan"},
  {code: "CTS", name: "New Chitose Airport", city: "Sapporo, Japan"},
  {code: "FUK", name: "Fukuoka Airport", city: "Fukuoka, Japan"},
  {code: "NGO", name: "Chubu Centrair International Airport", city: "Nagoya, Japan"},
  {code: "ICN", name: "Incheon International Airport", city: "Seoul, South Korea"},
  {code: "GMP", name: "Gimpo International Airport", city: "Seoul, South Korea"},
  {code: "PEK", name: "Beijing Capital International Airport", city: "Beijing, China"},
  {code: "PKX", name: "Beijing Daxing International Airport", city: "Beijing, China"},
  {code: "PVG", name: "Shanghai Pudong International Airport", city: "Shanghai, China"},
  {code: "SHA", name: "Shanghai Hongqiao International Airport", city: "Shanghai, China"},
  {code: "CAN", name: "Guangzhou Baiyun International Airport", city: "Guangzhou, China"},
  {code: "HKG", name: "Hong Kong International Airport", city: "Hong Kong"},
  {code: "SZX", name: "Shenzhen Bao'an International Airport", city: "Shenzhen, China"},
  {code: "CTU", name: "Chengdu Shuangliu International Airport", city: "Chengdu, China"},
  {code: "TPE", name: "Taiwan Taoyuan International Airport", city: "Taipei, Taiwan"},
  {code: "MFM", name: "Macau International Airport", city: "Macau"},
  // Asia - Southeast
  {code: "SIN", name: "Singapore Changi Airport", city: "Singapore"},
  {code: "BKK", name: "Suvarnabhumi Airport", city: "Bangkok, Thailand"},
  {code: "DMK", name: "Don Mueang International Airport", city: "Bangkok, Thailand"},
  {code: "HKT", name: "Phuket International Airport", city: "Phuket, Thailand"},
  {code: "CNX", name: "Chiang Mai International Airport", city: "Chiang Mai, Thailand"},
  {code: "KUL", name: "Kuala Lumpur International Airport", city: "Kuala Lumpur, Malaysia"},
  {code: "CGK", name: "Soekarno-Hatta International Airport", city: "Jakarta, Indonesia"},
  {code: "DPS", name: "Ngurah Rai International Airport", city: "Bali, Indonesia"},
  {code: "MNL", name: "Ninoy Aquino International Airport", city: "Manila, Philippines"},
  {code: "CEB", name: "Mactan-Cebu International Airport", city: "Cebu, Philippines"},
  {code: "SGN", name: "Tan Son Nhat International Airport", city: "Ho Chi Minh City, Vietnam"},
  {code: "HAN", name: "Noi Bai International Airport", city: "Hanoi, Vietnam"},
  {code: "DAD", name: "Da Nang International Airport", city: "Da Nang, Vietnam"},
  {code: "PNH", name: "Phnom Penh International Airport", city: "Phnom Penh, Cambodia"},
  {code: "REP", name: "Siem Reap International Airport", city: "Siem Reap, Cambodia"},
  {code: "RGN", name: "Yangon International Airport", city: "Yangon, Myanmar"},
  {code: "VTE", name: "Wattay International Airport", city: "Vientiane, Laos"},
  // Asia - South
  {code: "DEL", name: "Indira Gandhi International Airport", city: "New Delhi, India"},
  {code: "BOM", name: "Chhatrapati Shivaji Maharaj International Airport", city: "Mumbai, India"},
  {code: "BLR", name: "Kempegowda International Airport", city: "Bangalore, India"},
  {code: "MAA", name: "Chennai International Airport", city: "Chennai, India"},
  {code: "CCU", name: "Netaji Subhas Chandra Bose International Airport", city: "Kolkata, India"},
  {code: "HYD", name: "Rajiv Gandhi International Airport", city: "Hyderabad, India"},
  {code: "COK", name: "Cochin International Airport", city: "Kochi, India"},
  {code: "GOI", name: "Goa International Airport", city: "Goa, India"},
  {code: "CMB", name: "Bandaranaike International Airport", city: "Colombo, Sri Lanka"},
  {code: "KTM", name: "Tribhuvan International Airport", city: "Kathmandu, Nepal"},
  {code: "DAC", name: "Hazrat Shahjalal International Airport", city: "Dhaka, Bangladesh"},
  {code: "ISB", name: "Islamabad International Airport", city: "Islamabad, Pakistan"},
  {code: "KHI", name: "Jinnah International Airport", city: "Karachi, Pakistan"},
  {code: "MLE", name: "Velana International Airport", city: "Malé, Maldives"},
  // Asia - Central
  {code: "TAS", name: "Tashkent International Airport", city: "Tashkent, Uzbekistan"},
  {code: "ALA", name: "Almaty International Airport", city: "Almaty, Kazakhstan"},
  {code: "NQZ", name: "Nursultan Nazarbayev International Airport", city: "Astana, Kazakhstan"},
  {code: "TBS", name: "Tbilisi International Airport", city: "Tbilisi, Georgia"},
  {code: "EVN", name: "Zvartnots International Airport", city: "Yerevan, Armenia"},
  {code: "GYD", name: "Heydar Aliyev International Airport", city: "Baku, Azerbaijan"},
  // Oceania
  {code: "SYD", name: "Sydney Kingsford Smith Airport", city: "Sydney, Australia"},
  {code: "MEL", name: "Melbourne Airport", city: "Melbourne, Australia"},
  {code: "BNE", name: "Brisbane Airport", city: "Brisbane, Australia"},
  {code: "PER", name: "Perth Airport", city: "Perth, Australia"},
  {code: "ADL", name: "Adelaide Airport", city: "Adelaide, Australia"},
  {code: "CNS", name: "Cairns Airport", city: "Cairns, Australia"},
  {code: "AKL", name: "Auckland Airport", city: "Auckland, New Zealand"},
  {code: "CHC", name: "Christchurch Airport", city: "Christchurch, New Zealand"},
  {code: "WLG", name: "Wellington Airport", city: "Wellington, New Zealand"},
  {code: "ZQN", name: "Queenstown Airport", city: "Queenstown, New Zealand"},
  {code: "NAN", name: "Nadi International Airport", city: "Nadi, Fiji"},
  {code: "PPT", name: "Faa'a International Airport", city: "Papeete, French Polynesia"},
  {code: "NOU", name: "La Tontouta International Airport", city: "Nouméa, New Caledonia"},
];

const VALID_GUESSES = [
  "AAA","AAB","AAC","AAD","AAE","AAF","AAH","AAI","AAJ","AAK",
  "AAL","AAM","AAN","AAO","AAP","AAQ","AAR","AAS","AAT","AAU",
  "AAV","AAX","AAY","AAZ","ABA","ABB","ABC","ABD","ABE","ABF",
  "ABG","ABH","ABI","ABJ","ABK","ABL","ABM","ABN","ABO","ABP",
  "ABQ","ABR","ABS","ABT","ABU","ABV","ABX","ABY","ABZ","ACA",
  "ACB","ACC","ACD","ACE","ACF","ACH","ACI","ACJ","ACK","ACM",
  "ACN","ACO","ACP","ACR","ACS","ACT","ACU","ACV","ACX","ACY",
  "ACZ","ADA","ADB","ADC","ADD","ADE","ADF","ADG","ADH","ADI",
  "ADJ","ADK","ADL","ADM","ADO","ADP","ADQ","ADR","ADS","ADT",
  "ADU","ADV","ADW","ADX","ADY","ADZ","AEA","AEB","AEE","AEG",
  "AEH","AEI","AEK","AEL","AEM","AEO","AEP","AEQ","AER","AES",
  "AET","AEU","AEX","AEY","AFA","AFD","AFF","AFI","AFK","AFL",
  "AFN","AFO","AFR","AFS","AFT","AFW","AFY","AFZ","AGA","AGB",
  "AGC","AGD","AGE","AGF","AGG","AGH","AGI","AGJ","AGK","AGL",
  "AGM","AGN","AGO","AGP","AGQ","AGR","AGS","AGT","AGU","AGV",
  "AGW","AGX","AGZ","AHA","AHB","AHC","AHD","AHE","AHF","AHG",
  "AHH","AHI","AHJ","AHL","AHM","AHN","AHO","AHS","AHU","AHY",
  "AIA","AIC","AID","AIE","AIF","AIG","AIH","AII","AIK","AIL",
  "AIM","AIN","AIO","AIP","AIR","AIS","AIT","AIU","AIV","AIW",
  "AIY","AIZ","AJA","AJF","AJI","AJJ","AJK","AJL","AJN","AJR",
  "AJS","AJU","AJY","AKA","AKB","AKC","AKD","AKE","AKF","AKG",
  "AKH","AKI","AKJ","AKK","AKL","AKM","AKN","AKO","AKP","AKQ",
  "AKR","AKS","AKT","AKU","AKV","AKW","AKX","AKY","ALA","ALB",
  "ALC","ALD","ALE","ALF","ALG","ALH","ALI","ALJ","ALL","ALM",
  "ALN","ALO","ALP","ALQ","ALR","ALS","ALT","ALU","ALW","ALX",
  "ALY","ALZ","AMA","AMB","AMC","AMD","AME","AMF","AMH","AMI",
  "AMJ","AMK","AML","AMM","AMN","AMO","AMP","AMQ","AMS","AMT",
  "AMU","AMV","AMW","AMX","AMY","AMZ","ANA","ANB","ANC","AND",
  "ANE","ANF","ANG","ANI","ANJ","ANK","ANL","ANM","ANN","ANO",
  "ANP","ANQ","ANR","ANS","ANT","ANU","ANV","ANW","ANX","ANY",
  "ANZ","AOB","AOC","AOD","AOE","AOG","AOH","AOI","AOJ","AOK",
  "AOL","AOM","AOO","AOP","AOQ","AOR","AOS","AOT","AOU","APA",
  "APB","APC","APD","APF","APG","APH","API","APJ","APK","APL",
  "APN","APO","APP","APQ","APR","APS","APT","APU","APV","APW",
  "APX","APY","APZ","AQA","AQB","AQG","AQI","AQJ","AQM","AQP",
  "AQY","ARA","ARB","ARC","ARD","ARE","ARF","ARG","ARH","ARI",
  "ARK","ARL","ARM","ARN","ARO","ARP","ARQ","ARR","ARS","ART",
  "ARU","ARV","ARW","ARX","ARY","ARZ","ASA","ASB","ASC","ASD",
  "ASE","ASF","ASG","ASH","ASI","ASJ","ASK","ASL","ASM","ASN",
  "ASO","ASP","ASQ","ASR","ASS","AST","ASU","ASV","ASW","ASX",
  "ASY","ASZ","ATA","ATB","ATC","ATD","ATE","ATF","ATG","ATH",
  "ATI","ATJ","ATK","ATL","ATM","ATN","ATO","ATP","ATQ","ATR",
  "ATS","ATT","ATU","ATV","ATW","ATX","ATY","ATZ","AUA","AUC",
  "AUD","AUE","AUF","AUG","AUH","AUI","AUJ","AUK","AUL","AUM",
  "AUN","AUO","AUP","AUQ","AUR","AUS","AUT","AUU","AUV","AUW",
  "AUX","AUY","AUZ","AVA","AVB","AVG","AVI","AVK","AVL","AVN",
  "AVO","AVP","AVR","AVU","AVV","AVW","AVX","AWA","AWB","AWD",
  "AWE","AWK","AWM","AWN","AWP","AWR","AWZ","AXA","AXB","AXC",
  "AXD","AXE","AXF","AXG","AXJ","AXK","AXL","AXM","AXN","AXO",
  "AXP","AXR","AXS","AXT","AXU","AXV","AXX","AYA","AYC","AYD",
  "AYG","AYI","AYJ","AYK","AYL","AYM","AYN","AYO","AYP","AYQ",
  "AYR","AYS","AYT","AYU","AYW","AYX","AYY","AZA","AZB","AZD",
  "AZG","AZH","AZI","AZJ","AZL","AZN","AZO","AZP","AZR","AZS",
  "AZT","AZZ","BAB","BAC","BAD","BAF","BAG","BAH","BAI","BAJ",
  "BAL","BAM","BAN","BAQ","BAR","BAS","BAT","BAU","BAV","BAX",
  "BAY","BAZ","BBA","BBB","BBC","BBD","BBG","BBH","BBI","BBJ",
  "BBK","BBL","BBM","BBN","BBO","BBP","BBQ","BBR","BBS","BBT",
  "BBU","BBV","BBW","BBX","BBY","BBZ","BCA","BCB","BCC","BCD",
  "BCE","BCF","BCG","BCH","BCI","BCJ","BCK","BCL","BCM","BCN",
  "BCO","BCP","BCQ","BCR","BCS","BCT","BCU","BCV","BCW","BCX",
  "BCZ","BDA","BDB","BDC","BDD","BDE","BDF","BDG","BDH","BDI",
  "BDJ","BDK","BDL","BDM","BDN","BDO","BDP","BDQ","BDR","BDS",
  "BDT","BDU","BDV","BDW","BDX","BDY","BDZ","BEB","BEC","BED",
  "BEE","BEF","BEG","BEH","BEI","BEJ","BEK","BEL","BEM","BEN",
  "BEO","BEP","BEQ","BER","BES","BET","BEU","BEV","BEW","BEX",
  "BEY","BEZ","BFA","BFC","BFD","BFE","BFF","BFG","BFH","BFI",
  "BFJ","BFK","BFL","BFM","BFN","BFO","BFP","BFQ","BFR","BFS",
  "BFT","BFU","BFV","BFW","BFX","BFY","BGA","BGB","BGC","BGD",
  "BGE","BGF","BGG","BGH","BGI","BGJ","BGK","BGL","BGM","BGN",
  "BGO","BGQ","BGR","BGS","BGT","BGU","BGV","BGW","BGX","BGY",
  "BGZ","BHA","BHB","BHC","BHD","BHE","BHF","BHG","BHH","BHI",
  "BHJ","BHK","BHL","BHM","BHN","BHO","BHP","BHQ","BHR","BHS",
  "BHT","BHU","BHV","BHW","BHX","BHY","BIA","BIB","BIC","BID",
  "BIE","BIF","BIG","BIH","BII","BIJ","BIK","BIL","BIM","BIN",
  "BIO","BIP","BIQ","BIR","BIS","BIT","BIU","BIV","BIW","BIX",
  "BIY","BJA","BJB","BJC","BJE","BJF","BJH","BJI","BJJ","BJK",
  "BJL","BJM","BJO","BJP","BJQ","BJR","BJT","BJU","BJV","BJW",
  "BJX","BJY","BJZ","BKA","BKB","BKC","BKD","BKE","BKF","BKG",
  "BKH","BKI","BKJ","BKK","BKL","BKM","BKN","BKO","BKP","BKQ",
  "BKR","BKS","BKT","BKU","BKV","BKW","BKX","BKY","BKZ","BLA",
  "BLB","BLC","BLD","BLE","BLF","BLG","BLH","BLI","BLJ","BLK",
  "BLL","BLM","BLN","BLO","BLP","BLQ","BLR","BLS","BLT","BLU",
  "BLV","BLW","BLX","BLY","BLZ","BMA","BMB","BMC","BMD","BME",
  "BMF","BMG","BMH","BMI","BMJ","BMK","BML","BMM","BMN","BMO",
  "BMP","BMQ","BMR","BMS","BMT","BMU","BMV","BMW","BMX","BMY",
  "BMZ","BNA","BNB","BNC","BND","BNE","BNF","BNG","BNH","BNI",
  "BNJ","BNK","BNL","BNM","BNN","BNO","BNP","BNR","BNS","BNT",
  "BNU","BNV","BNW","BNX","BNY","BOA","BOB","BOC","BOD","BOE",
  "BOG","BOH","BOI","BOJ","BOK","BOM","BON","BOO","BOP","BOR",
  "BOS","BOT","BOU","BOV","BOW","BOX","BOY","BOZ","BPA","BPC",
  "BPD","BPE","BPF","BPG","BPH","BPI","BPK","BPL","BPM","BPN",
  "BPS","BPT","BPX","BPY","BQA","BQB","BQE","BQG","BQH","BQI",
  "BQJ","BQK","BQL","BQN","BQO","BQQ","BQS","BQT","BQU","BQV",
  "BQW","BRA","BRB","BRC","BRD","BRE","BRG","BRH","BRI","BRK",
  "BRL","BRM","BRN","BRO","BRP","BRQ","BRR","BRS","BRT","BRU",
  "BRV","BRW","BRX","BRY","BSA","BSB","BSC","BSD","BSE","BSF",
  "BSG","BSI","BSJ","BSK","BSL","BSM","BSN","BSO","BSP","BSQ",
  "BSR","BSS","BST","BSU","BSV","BSW","BSX","BSY","BSZ","BTA",
  "BTB","BTC","BTD","BTE","BTF","BTG","BTH","BTI","BTJ","BTK",
  "BTL","BTM","BTN","BTO","BTP","BTQ","BTR","BTS","BTT","BTU",
  "BTV","BTW","BTX","BTY","BTZ","BUA","BUB","BUC","BUD","BUF",
  "BUG","BUI","BUJ","BUK","BUL","BUM","BUN","BUO","BUP","BUQ",
  "BUR","BUS","BUT","BUU","BUV","BUW","BUX","BUY","BUZ","BVA",
  "BVB","BVC","BVE","BVG","BVH","BVI","BVJ","BVK","BVL","BVM",
  "BVO","BVS","BVU","BVV","BVW","BVX","BVY","BVZ","BWA","BWB",
  "BWC","BWD","BWE","BWF","BWG","BWH","BWI","BWJ","BWK","BWL",
  "BWM","BWN","BWO","BWP","BWQ","BWT","BWU","BWW","BWX","BXA",
  "BXB","BXD","BXE","BXF","BXG","BXH","BXI","BXJ","BXK","BXL",
  "BXM","BXN","BXO","BXP","BXR","BXS","BXT","BXU","BXV","BXW",
  "BXX","BXY","BXZ","BYA","BYB","BYC","BYD","BYF","BYG","BYH",
  "BYI","BYJ","BYK","BYL","BYM","BYN","BYO","BYP","BYQ","BYR",
  "BYS","BYT","BYU","BYV","BYW","BYX","BZA","BZB","BZC","BZD",
  "BZE","BZF","BZG","BZH","BZI","BZJ","BZK","BZL","BZM","BZN",
  "BZO","BZP","BZR","BZT","BZU","BZV","BZX","BZY","BZZ","CAA",
  "CAB","CAC","CAD","CAE","CAF","CAG","CAH","CAI","CAJ","CAK",
  "CAL","CAM","CAN","CAO","CAP","CAQ","CAR","CAT","CAU","CAV",
  "CAW","CAX","CAY","CAZ","CBA","CBB","CBC","CBD","CBE","CBF",
  "CBG","CBH","CBI","CBJ","CBK","CBL","CBM","CBN","CBO","CBQ",
  "CBR","CBS","CBT","CBU","CBV","CBW","CBX","CBY","CBZ","CCA",
  "CCB","CCC","CCD","CCE","CCF","CCG","CCH","CCI","CCJ","CCK",
  "CCL","CCM","CCN","CCO","CCP","CCR","CCS","CCU","CCV","CCW",
  "CCX","CCY","CCZ","CDA","CDB","CDC","CDD","CDE","CDG","CDH",
  "CDI","CDJ","CDK","CDL","CDN","CDO","CDP","CDQ","CDR","CDS",
  "CDT","CDU","CDV","CDW","CDY","CEA","CEB","CEC","CED","CEE",
  "CEF","CEG","CEH","CEI","CEJ","CEK","CEL","CEM","CEN","CEO",
  "CEP","CEQ","CER","CES","CET","CEU","CEV","CEW","CEX","CEY",
  "CEZ","CFB","CFC","CFD","CFE","CFF","CFG","CFH","CFI","CFK",
  "CFM","CFN","CFO","CFP","CFQ","CFR","CFS","CFT","CFU","CFV",
  "CGA","CGB","CGC","CGD","CGE","CGF","CGG","CGH","CGI","CGJ",
  "CGK","CGL","CGM","CGN","CGO","CGP","CGQ","CGR","CGS","CGV",
  "CGX","CGY","CGZ","CHA","CHB","CHC","CHD","CHE","CHF","CHG",
  "CHH","CHJ","CHK","CHL","CHM","CHN","CHO","CHP","CHQ","CHR",
  "CHS","CHT","CHU","CHX","CHY","CHZ","CIA","CIC","CID","CIE",
  "CIF","CIG","CIH","CII","CIJ","CIK","CIL","CIM","CIN","CIO",
  "CIP","CIQ","CIR","CIS","CIT","CIU","CIW","CIX","CIY","CIZ",
  "CJA","CJB","CJC","CJD","CJF","CJH","CJJ","CJL","CJM","CJN",
  "CJS","CJT","CJU","CJZ","CKA","CKB","CKC","CKD","CKE","CKG",
  "CKH","CKI","CKK","CKL","CKM","CKN","CKO","CKR","CKS","CKT",
  "CKU","CKV","CKW","CKX","CKY","CKZ","CLA","CLD","CLE","CLG",
  "CLH","CLI","CLJ","CLK","CLL","CLM","CLN","CLO","CLP","CLQ",
  "CLR","CLS","CLT","CLU","CLV","CLW","CLX","CLY","CLZ","CMA",
  "CMB","CMC","CMD","CME","CMF","CMG","CMH","CMI","CMJ","CMK",
  "CML","CMM","CMN","CMO","CMP","CMQ","CMR","CMS","CMT","CMU",
  "CMV","CMW","CMX","CMY","CMZ","CNA","CNB","CNC","CND","CNE",
  "CNF","CNG","CNH","CNI","CNJ","CNK","CNL","CNM","CNN","CNO",
  "CNP","CNQ","CNR","CNS","CNT","CNU","CNV","CNW","CNX","CNY",
  "CNZ","COA","COB","COC","COD","COE","COF","COG","COH","COI",
  "COJ","COK","COL","COM","CON","COO","COP","COQ","COR","COS",
  "COT","COU","COV","COW","COX","COY","COZ","CPA","CPB","CPC",
  "CPD","CPE","CPF","CPG","CPH","CPI","CPL","CPM","CPN","CPO",
  "CPP","CPQ","CPR","CPS","CPT","CPU","CPV","CPX","CQA","CQD",
  "CQF","CQM","CQP","CQS","CQT","CQW","CRA","CRB","CRC","CRD",
  "CRE","CRF","CRG","CRH","CRI","CRJ","CRK","CRL","CRM","CRO",
  "CRP","CRQ","CRR","CRS","CRT","CRU","CRV","CRW","CRX","CRY",
  "CRZ","CSA","CSB","CSC","CSD","CSE","CSF","CSG","CSH","CSI",
  "CSK","CSM","CSN","CSO","CSQ","CSR","CSS","CST","CSU","CSV",
  "CSW","CSX","CSY","CSZ","CTA","CTB","CTC","CTD","CTE","CTF",
  "CTG","CTH","CTI","CTK","CTL","CTM","CTN","CTO","CTP","CTQ",
  "CTR","CTS","CTT","CTU","CTV","CTW","CTX","CTY","CTZ","CUA",
  "CUB","CUC","CUD","CUE","CUF","CUG","CUH","CUI","CUJ","CUK",
  "CUL","CUM","CUN","CUO","CUP","CUQ","CUR","CUS","CUT","CUU",
  "CUV","CUY","CUZ","CVB","CVC","CVE","CVF","CVG","CVH","CVI",
  "CVJ","CVL","CVM","CVN","CVO","CVQ","CVS","CVT","CVU","CWA",
  "CWB","CWC","CWE","CWF","CWI","CWJ","CWK","CWL","CWP","CWR",
  "CWS","CWT","CWW","CWX","CXA","CXB","CXC","CXF","CXH","CXI",
  "CXJ","CXL","CXM","CXN","CXO","CXP","CXQ","CXR","CXT","CXY",
  "CYA","CYB","CYC","CYD","CYF","CYG","CYI","CYL","CYM","CYO",
  "CYP","CYR","CYS","CYT","CYU","CYW","CYX","CYZ","CZA","CZB",
  "CZC","CZE","CZF","CZH","CZJ","CZK","CZL","CZM","CZN","CZO",
  "CZP","CZR","CZS","CZT","CZU","CZX","CZY","DAA","DAB","DAC",
  "DAD","DAF","DAG","DAH","DAK","DAL","DAM","DAN","DAO","DAP",
  "DAR","DAS","DAT","DAU","DAV","DAX","DAY","DAZ","DBA","DBB",
  "DBC","DBD","DBK","DBM","DBN","DBO","DBP","DBQ","DBR","DBS",
  "DBT","DBU","DBV","DBY","DCA","DCF","DCI","DCK","DCM","DCN",
  "DCT","DCU","DCY","DDC","DDD","DDG","DDI","DDM","DDN","DDR",
  "DDU","DEA","DEB","DEC","DED","DEE","DEF","DEH","DEI","DEJ",
  "DEL","DEM","DEN","DEP","DEQ","DER","DES","DET","DEX","DEZ",
  "DFA","DFI","DFP","DFW","DGA","DGD","DGE","DGF","DGH","DGL",
  "DGM","DGN","DGO","DGP","DGR","DGT","DGU","DGW","DHA","DHB",
  "DHD","DHF","DHG","DHH","DHI","DHL","DHM","DHN","DHR","DHT",
  "DHX","DIA","DIB","DIE","DIG","DIJ","DIK","DIL","DIM","DIN",
  "DIO","DIP","DIQ","DIR","DIS","DIU","DIW","DIY","DJA","DJB",
  "DJE","DJG","DJJ","DJM","DJN","DJO","DJR","DJU","DKA","DKI",
  "DKK","DKR","DKS","DKV","DLA","DLC","DLD","DLE","DLF","DLG",
  "DLH","DLI","DLK","DLL","DLM","DLN","DLR","DLS","DLU","DLV",
  "DLY","DLZ","DMA","DMB","DMD","DME","DMK","DMM","DMN","DMO",
  "DMT","DMU","DNA","DNB","DND","DNF","DNG","DNH","DNK","DNL",
  "DNN","DNO","DNP","DNQ","DNR","DNS","DNU","DNV","DNX","DNZ",
  "DOA","DOB","DOD","DOE","DOG","DOH","DOI","DOK","DOL","DOM",
  "DON","DOO","DOP","DOR","DOU","DOV","DOX","DOY","DPA","DPB",
  "DPE","DPG","DPL","DPO","DPS","DPT","DQA","DQM","DRA","DRB",
  "DRC","DRD","DRE","DRF","DRG","DRH","DRI","DRJ","DRK","DRN",
  "DRO","DRP","DRR","DRS","DRT","DRU","DRV","DRW","DRY","DSC",
  "DSD","DSE","DSG","DSI","DSK","DSM","DSN","DSO","DSS","DST",
  "DSV","DSX","DSY","DTA","DTB","DTD","DTE","DTH","DTI","DTL",
  "DTM","DTN","DTR","DTU","DTW","DUA","DUB","DUC","DUD","DUE",
  "DUF","DUG","DUJ","DUK","DUM","DUQ","DUR","DUS","DUT","DVD",
  "DVK","DVL","DVN","DVO","DVP","DVR","DVT","DWA","DWB","DWC",
  "DWD","DWH","DWO","DWR","DWS","DXB","DXD","DXE","DXJ","DXN",
  "DXR","DYA","DYG","DYL","DYM","DYR","DYS","DYU","DYW","DZA",
  "DZH","DZI","DZN","DZO","DZU","EAA","EAB","EAE","EAL","EAM",
  "EAN","EAR","EAS","EAT","EAU","EAX","EBA","EBB","EBD","EBG",
  "EBH","EBJ","EBL","EBM","EBN","EBO","EBS","EBU","EBW","ECA",
  "ECG","ECH","ECI","ECN","ECO","ECP","ECR","ECS","ECV","EDA",
  "EDB","EDD","EDE","EDF","EDI","EDK","EDL","EDM","EDN","EDO",
  "EDQ","EDR","EDW","EEA","EED","EEK","EEN","EES","EFD","EFG",
  "EFK","EFL","EFW","EGA","EGC","EGE","EGH","EGI","EGL","EGM",
  "EGN","EGO","EGP","EGS","EGV","EGX","EHL","EHM","EHU","EIB",
  "EIE","EIH","EIK","EIL","EIN","EIS","EIY","EJA","EJH","EJN",
  "EJT","EKA","EKB","EKD","EKI","EKN","EKO","EKS","EKT","EKX",
  "ELA","ELB","ELC","ELD","ELE","ELF","ELG","ELH","ELI","ELJ",
  "ELK","ELL","ELM","ELN","ELO","ELP","ELQ","ELR","ELS","ELT",
  "ELU","ELV","ELW","ELX","ELY","ELZ","EMA","EMD","EME","EMG",
  "EMI","EMK","EML","EMM","EMN","EMO","EMP","EMR","EMS","EMT",
  "EMX","EMY","ENA","ENB","ENC","END","ENE","ENF","ENG","ENH",
  "ENI","ENJ","ENK","ENL","ENN","ENO","ENS","ENT","ENU","ENV",
  "ENW","ENY","EOH","EOI","EOK","EOR","EOS","EOZ","EPA","EPG",
  "EPH","EPL","EPR","EPT","EPU","EQS","ERA","ERB","ERC","ERD",
  "ERE","ERF","ERG","ERH","ERI","ERL","ERM","ERN","ERQ","ERR",
  "ERS","ERT","ERU","ERV","ERZ","ESA","ESB","ESC","ESD","ESE",
  "ESF","ESG","ESH","ESK","ESL","ESM","ESN","ESO","ESR","ESS",
  "EST","ESU","ESW","ETB","ETD","ETE","ETH","ETL","ETM","ETN",
  "ETR","ETS","ETZ","EUA","EUC","EUE","EUF","EUG","EUM","EUN",
  "EUO","EUQ","EUX","EVD","EVE","EVG","EVH","EVM","EVN","EVV",
  "EVW","EVX","EWB","EWE","EWI","EWK","EWN","EWO","EWR","EXI",
  "EXM","EXT","EYA","EYK","EYL","EYP","EYR","EYS","EYW","EZE",
  "EZS","EZV","FAA","FAB","FAC","FAE","FAF","FAG","FAH","FAI",
  "FAJ","FAK","FAM","FAN","FAO","FAQ","FAR","FAT","FAU","FAV",
  "FAY","FAZ","FBA","FBD","FBE","FBG","FBK","FBL","FBM","FBR",
  "FBS","FBY","FCA","FCB","FCH","FCM","FCN","FCO","FCS","FCY",
  "FDA","FDF","FDH","FDK","FDO","FDR","FDU","FDY","FEB","FEC",
  "FEG","FEJ","FEL","FEN","FEP","FET","FEZ","FFA","FFD","FFL",
  "FFM","FFO","FFT","FFU","FGD","FGI","FGL","FGU","FHU","FHZ",
  "FID","FIE","FIG","FIH","FIK","FIL","FIN","FIZ","FJR","FKB",
  "FKI","FKJ","FKL","FKN","FKQ","FKS","FLA","FLB","FLD","FLF",
  "FLG","FLH","FLL","FLM","FLN","FLO","FLP","FLR","FLS","FLT",
  "FLV","FLW","FLX","FLY","FLZ","FMA","FME","FMG","FMH","FMI",
  "FMM","FMN","FMO","FMS","FMT","FMU","FMY","FNA","FNB","FNC",
  "FND","FNE","FNG","FNH","FNI","FNJ","FNL","FNR","FNT","FNU",
  "FOA","FOB","FOC","FOD","FOE","FOG","FOK","FOM","FON","FOO",
  "FOR","FOS","FOT","FOU","FOY","FPO","FPR","FPY","FRA","FRB",
  "FRC","FRD","FRE","FRG","FRH","FRI","FRJ","FRK","FRL","FRM",
  "FRN","FRO","FRQ","FRR","FRS","FRT","FRU","FRW","FRY","FRZ",
  "FSC","FSD","FSH","FSI","FSK","FSL","FSM","FSP","FSS","FST",
  "FSU","FSZ","FTA","FTE","FTI","FTK","FTU","FTW","FTX","FTY",
  "FUB","FUE","FUG","FUJ","FUK","FUL","FUM","FUN","FUO","FUT",
  "FVL","FVM","FVR","FWA","FWH","FWL","FXE","FXO","FXY","FYJ",
  "FYM","FYN","FYT","FYU","FYV","FZL","FZO","GAA","GAB","GAC",
  "GAD","GAE","GAF","GAG","GAH","GAI","GAJ","GAL","GAM","GAN",
  "GAO","GAP","GAQ","GAR","GAS","GAU","GAV","GAW","GAX","GAY",
  "GAZ","GBA","GBB","GBC","GBD","GBE","GBF","GBG","GBH","GBI",
  "GBJ","GBK","GBL","GBM","GBP","GBR","GBT","GBU","GBV","GBW",
  "GBZ","GCA","GCC","GCD","GCH","GCI","GCJ","GCK","GCM","GCN",
  "GCT","GCV","GCW","GCY","GDB","GDC","GDD","GDE","GDH","GDI",
  "GDL","GDM","GDN","GDO","GDP","GDQ","GDR","GDT","GDV","GDW",
  "GDX","GDZ","GEA","GEB","GEC","GED","GEE","GEF","GEG","GEL",
  "GEM","GEO","GER","GES","GET","GEV","GEW","GEX","GEY","GFA",
  "GFD","GFE","GFF","GFK","GFL","GFN","GFO","GFR","GFY","GGB",
  "GGC","GGD","GGE","GGF","GGG","GGH","GGJ","GGM","GGN","GGO",
  "GGR","GGS","GGT","GGW","GHA","GHB","GHC","GHE","GHF","GHK",
  "GHM","GHN","GHS","GHT","GHU","GHV","GIB","GIC","GID","GIF",
  "GIG","GII","GIL","GIM","GIR","GIS","GIT","GIU","GIY","GIZ",
  "GJA","GJL","GJM","GJR","GJT","GKA","GKD","GKE","GKH","GKK",
  "GKL","GKN","GKT","GLA","GLB","GLC","GLD","GLE","GLF","GLG",
  "GLH","GLI","GLK","GLL","GLM","GLN","GLO","GLP","GLR","GLS",
  "GLT","GLU","GLV","GLW","GLX","GLZ","GMA","GMB","GMC","GMD",
  "GME","GMI","GML","GMM","GMN","GMO","GMP","GMQ","GMR","GMS",
  "GMT","GMU","GMV","GMZ","GNA","GNB","GND","GNE","GNF","GNG",
  "GNI","GNJ","GNM","GNN","GNR","GNS","GNT","GNU","GNV","GNY",
  "GNZ","GOA","GOB","GOC","GOE","GOG","GOH","GOI","GOJ","GOK",
  "GOL","GOM","GON","GOO","GOP","GOQ","GOR","GOS","GOT","GOU",
  "GOV","GOX","GOY","GOZ","GPA","GPB","GPD","GPI","GPL","GPN",
  "GPO","GPS","GPT","GPZ","GQQ","GRA","GRB","GRC","GRD","GRE",
  "GRF","GRG","GRI","GRJ","GRK","GRL","GRM","GRN","GRO","GRP",
  "GRQ","GRR","GRS","GRT","GRU","GRV","GRW","GRX","GRY","GRZ",
  "GSA","GSB","GSC","GSE","GSH","GSI","GSJ","GSL","GSM","GSN",
  "GSO","GSP","GSQ","GSR","GSS","GST","GSV","GTA","GTC","GTE",
  "GTF","GTG","GTI","GTK","GTN","GTO","GTP","GTR","GTS","GTT",
  "GTY","GTZ","GUA","GUB","GUC","GUD","GUE","GUF","GUG","GUH",
  "GUI","GUJ","GUL","GUM","GUO","GUP","GUQ","GUR","GUS","GUT",
  "GUU","GUV","GUW","GUX","GUY","GUZ","GVA","GVE","GVI","GVL",
  "GVN","GVP","GVR","GVT","GVX","GWA","GWD","GWE","GWL","GWO",
  "GWS","GWT","GWV","GWY","GXF","GXG","GXH","GXM","GXQ","GXX",
  "GXY","GYA","GYB","GYD","GYE","GYG","GYI","GYL","GYM","GYN",
  "GYO","GYP","GYR","GYS","GYU","GYY","GYZ","GZA","GZG","GZI",
  "GZM","GZO","GZP","GZT","GZW","HAA","HAB","HAC","HAD","HAE",
  "HAF","HAH","HAI","HAJ","HAK","HAL","HAM","HAN","HAO","HAP",
  "HAQ","HAR","HAS","HAT","HAU","HAV","HAW","HAY","HAZ","HBA",
  "HBB","HBD","HBE","HBG","HBH","HBK","HBQ","HBR","HBT","HBU",
  "HBX","HCA","HCC","HCJ","HCM","HCN","HCQ","HCR","HCW","HCZ",
  "HDD","HDE","HDF","HDG","HDH","HDI","HDK","HDM","HDN","HDO",
  "HDR","HDS","HDY","HEA","HEB","HED","HEE","HEG","HEH","HEI",
  "HEK","HEL","HEM","HEN","HEO","HER","HES","HET","HEW","HEX",
  "HEY","HEZ","HFA","HFD","HFE","HFF","HFN","HFS","HFT","HGA",
  "HGD","HGE","HGH","HGI","HGL","HGN","HGO","HGR","HGS","HGT",
  "HGU","HGZ","HHE","HHH","HHI","HHN","HHP","HHQ","HHR","HHZ",
  "HIA","HIB","HID","HIE","HIF","HIG","HII","HIJ","HIL","HIM",
  "HIN","HIO","HIP","HIR","HIS","HIT","HIW","HJB","HJJ","HJR",
  "HJT","HKA","HKB","HKD","HKG","HKK","HKN","HKR","HKS","HKT",
  "HKY","HLA","HLB","HLC","HLD","HLE","HLF","HLG","HLH","HLI",
  "HLJ","HLL","HLM","HLN","HLP","HLR","HLS","HLT","HLV","HLW",
  "HLZ","HMA","HMB","HME","HMG","HMI","HMJ","HMN","HMO","HMR",
  "HMS","HMT","HMV","HMY","HNA","HNB","HNC","HND","HNH","HNI",
  "HNL","HNM","HNN","HNS","HNY","HOA","HOB","HOC","HOD","HOE",
  "HOF","HOG","HOH","HOI","HOK","HOM","HON","HOO","HOP","HOQ",
  "HOR","HOS","HOT","HOU","HOX","HPA","HPB","HPE","HPG","HPH",
  "HPN","HPR","HPT","HPV","HPY","HQL","HQM","HQQ","HRA","HRB",
  "HRC","HRE","HRF","HRG","HRH","HRI","HRK","HRL","HRM","HRO",
  "HRR","HRS","HRT","HRY","HRZ","HSA","HSB","HSC","HSF","HSG",
  "HSH","HSI","HSJ","HSK","HSL","HSM","HSN","HSP","HSR","HSS",
  "HST","HSV","HSZ","HTA","HTG","HTH","HTI","HTL","HTM","HTN",
  "HTO","HTR","HTS","HTT","HTU","HTV","HTW","HTY","HTZ","HUA",
  "HUB","HUC","HUD","HUE","HUG","HUH","HUI","HUJ","HUK","HUL",
  "HUM","HUN","HUO","HUQ","HUS","HUT","HUU","HUV","HUW","HUX",
  "HUY","HUZ","HVA","HVB","HVD","HVE","HVG","HVK","HVN","HVR",
  "HVS","HWA","HWD","HWI","HWK","HWN","HWO","HWR","HXD","HXX",
  "HYA","HYC","HYD","HYF","HYG","HYL","HYN","HYR","HYS","HYV",
  "HZA","HZB","HZG","HZH","HZK","HZL","HZP","HZU","HZV","IAA",
  "IAB","IAD","IAG","IAH","IAL","IAM","IAN","IAO","IAQ","IAR",
  "IAS","IAX","IBA","IBB","IBE","IBI","IBL","IBM","IBO","IBP",
  "IBR","IBZ","ICA","ICC","ICI","ICK","ICL","ICN","ICO","ICS",
  "ICT","ICY","IDA","IDB","IDF","IDG","IDH","IDI","IDK","IDN",
  "IDO","IDP","IDR","IDY","IEG","IEJ","IES","IEV","IFA","IFF",
  "IFH","IFJ","IFL","IFN","IFO","IFP","IFU","IGA","IGB","IGD",
  "IGE","IGG","IGH","IGL","IGM","IGN","IGO","IGR","IGS","IGT",
  "IGU","IHC","IHN","IHO","IHR","IHU","IIA","IIL","IIS","IJK",
  "IJU","IJX","IKA","IKB","IKE","IKG","IKI","IKK","IKL","IKO",
  "IKP","IKS","IKT","IKU","ILA","ILD","ILE","ILF","ILG","ILH",
  "ILI","ILK","ILL","ILM","ILN","ILO","ILP","ILQ","ILR","ILS",
  "ILU","ILY","ILZ","IMB","IMD","IMF","IMG","IMI","IMK","IML",
  "IMM","IMN","IMO","IMP","IMQ","IMT","INA","INB","INC","IND",
  "INE","INF","ING","INH","INI","INJ","INK","INL","INM","INN",
  "INO","INQ","INS","INT","INU","INV","INW","INX","INY","INZ",
  "IOA","IOK","IOM","ION","IOP","IOQ","IOR","IOS","IOT","IOW",
  "IPA","IPC","IPE","IPG","IPH","IPI","IPL","IPN","IPT","IPU",
  "IPZ","IQA","IQM","IQN","IQQ","IQT","IRA","IRB","IRC","IRD",
  "IRE","IRG","IRI","IRJ","IRK","IRM","IRN","IRO","IRP","IRS",
  "IRU","IRZ","ISA","ISB","ISC","ISD","ISE","ISG","ISI","ISJ",
  "ISK","ISL","ISM","ISN","ISO","ISP","ISQ","ISS","IST","ISU",
  "ISW","ITA","ITB","ITE","ITH","ITI","ITJ","ITK","ITM","ITN",
  "ITO","ITP","ITQ","ITR","ITU","IUA","IUE","IUI","IUL","IUP",
  "IVA","IVC","IVD","IVG","IVI","IVL","IVO","IVR","IVW","IWA",
  "IWD","IWJ","IWK","IWO","IWS","IXA","IXB","IXC","IXD","IXE",
  "IXG","IXH","IXI","IXJ","IXK","IXL","IXM","IXN","IXP","IXQ",
  "IXR","IXS","IXT","IXU","IXV","IXW","IXX","IXY","IXZ","IYK",
  "IZA","IZE","IZM","IZO","IZT","JAA","JAB","JAC","JAD","JAE",
  "JAF","JAG","JAH","JAI","JAK","JAL","JAM","JAN","JAP","JAQ",
  "JAR","JAS","JAT","JAU","JAV","JAW","JAX","JBB","JBK","JBQ",
  "JBR","JBS","JBT","JCB","JCH","JCI","JCK","JCL","JCM","JCO",
  "JCR","JCS","JCT","JCU","JCY","JDA","JDE","JDF","JDG","JDH",
  "JDN","JDO","JDR","JDZ","JED","JEE","JEF","JEG","JEJ","JEK",
  "JEQ","JER","JFK","JFM","JFN","JFR","JGA","JGB","JGD","JGN",
  "JGO","JGR","JGS","JHB","JHF","JHG","JHL","JHM","JHN","JHQ",
  "JHS","JHW","JIA","JIB","JIC","JID","JIJ","JIK","JIL","JIM",
  "JIN","JIO","JIP","JIQ","JIR","JIU","JIW","JJD","JJG","JJI",
  "JJM","JJN","JJU","JKG","JKH","JKL","JKR","JKV","JLA","JLG",
  "JLN","JLR","JLS","JMA","JMB","JMJ","JMK","JMO","JMR","JMS",
  "JMU","JNA","JNB","JNG","JNI","JNJ","JNN","JNS","JNU","JNX",
  "JNZ","JOE","JOG","JOH","JOI","JOJ","JOK","JOL","JOM","JON",
  "JOP","JOS","JOT","JPA","JPE","JPN","JPO","JPR","JPY","JQA",
  "JQE","JRA","JRB","JRF","JRG","JRH","JRJ","JRK","JRN","JRO",
  "JRT","JSA","JSB","JSH","JSI","JSJ","JSK","JSM","JSO","JSR",
  "JST","JSU","JSY","JTA","JTC","JTI","JTN","JTR","JTY","JUA",
  "JUB","JUH","JUI","JUJ","JUK","JUL","JUM","JUN","JUO","JUR",
  "JUT","JUU","JUV","JUZ","JVA","JVI","JVL","JWA","JWN","JWO",
  "JXA","JXN","JYR","JYV","JZH","KAA","KAB","KAC","KAD","KAE",
  "KAF","KAG","KAI","KAJ","KAK","KAL","KAM","KAN","KAO","KAP",
  "KAQ","KAR","KAS","KAT","KAU","KAV","KAW","KAX","KAY","KAZ",
  "KBA","KBB","KBC","KBD","KBE","KBF","KBH","KBI","KBJ","KBK",
  "KBL","KBM","KBN","KBO","KBP","KBQ","KBR","KBS","KBT","KBU",
  "KBV","KBW","KBX","KBY","KBZ","KCA","KCB","KCC","KCD","KCE",
  "KCF","KCG","KCH","KCI","KCJ","KCK","KCL","KCM","KCN","KCO",
  "KCP","KCQ","KCR","KCS","KCT","KCU","KCY","KCZ","KDA","KDB",
  "KDC","KDD","KDE","KDH","KDI","KDJ","KDK","KDL","KDM","KDN",
  "KDO","KDP","KDQ","KDR","KDS","KDT","KDU","KDV","KDW","KDX",
  "KDY","KDZ","KEA","KEB","KEC","KED","KEE","KEF","KEG","KEH",
  "KEI","KEJ","KEK","KEL","KEM","KEN","KEO","KEP","KEQ","KER",
  "KES","KET","KEU","KEV","KEW","KEX","KEY","KEZ","KFA","KFE",
  "KFG","KFM","KFP","KFS","KFZ","KGA","KGB","KGC","KGD","KGE",
  "KGF","KGG","KGH","KGI","KGJ","KGK","KGL","KGM","KGN","KGO",
  "KGP","KGQ","KGR","KGS","KGT","KGU","KGW","KGX","KGY","KGZ",
  "KHA","KHC","KHD","KHE","KHG","KHH","KHI","KHJ","KHK","KHM",
  "KHN","KHO","KHQ","KHR","KHS","KHT","KHU","KHV","KHW","KHX",
  "KHY","KHZ","KIB","KIC","KID","KIE","KIF","KIG","KIH","KII",
  "KIJ","KIK","KIL","KIM","KIN","KIO","KIP","KIQ","KIR","KIS",
  "KIT","KIU","KIV","KIW","KIX","KIY","KJA","KJB","KJH","KJI",
  "KJJ","KJK","KJP","KJT","KJX","KKA","KKB","KKC","KKD","KKE",
  "KKG","KKH","KKI","KKJ","KKK","KKL","KKM","KKN","KKO","KKP",
  "KKQ","KKR","KKS","KKT","KKU","KKW","KKX","KKY","KKZ","KLB",
  "KLC","KLD","KLE","KLF","KLG","KLH","KLI","KLJ","KLK","KLL",
  "KLM","KLN","KLO","KLP","KLR","KLS","KLU","KLV","KLW","KLX",
  "KLY","KLZ","KMA","KMB","KMC","KME","KMF","KMG","KMH","KMI",
  "KMJ","KMK","KML","KMM","KMN","KMO","KMP","KMQ","KMR","KMS",
  "KMU","KMV","KMW","KMX","KMY","KMZ","KNA","KNB","KND","KNE",
  "KNF","KNG","KNH","KNI","KNJ","KNK","KNM","KNN","KNO","KNP",
  "KNQ","KNR","KNS","KNT","KNU","KNW","KNX","KNY","KNZ","KOA",
  "KOC","KOD","KOE","KOF","KOH","KOI","KOJ","KOK","KOM","KOO",
  "KOP","KOQ","KOR","KOS","KOT","KOU","KOV","KOW","KOX","KOY",
  "KOZ","KPA","KPB","KPC","KPE","KPF","KPI","KPL","KPM","KPN",
  "KPO","KPP","KPR","KPS","KPT","KPV","KPW","KPY","KQA","KQH",
  "KQL","KQR","KQT","KRA","KRB","KRC","KRD","KRE","KRF","KRG",
  "KRH","KRI","KRJ","KRK","KRL","KRM","KRN","KRO","KRP","KRQ",
  "KRR","KRS","KRT","KRU","KRV","KRW","KRX","KRY","KRZ","KSA",
  "KSB","KSC","KSD","KSE","KSF","KSH","KSI","KSJ","KSK","KSL",
  "KSM","KSN","KSO","KSP","KSQ","KSR","KSS","KSU","KSV","KSW",
  "KSX","KSY","KSZ","KTA","KTB","KTC","KTD","KTE","KTF","KTG",
  "KTH","KTI","KTJ","KTL","KTM","KTN","KTO","KTP","KTQ","KTR",
  "KTS","KTT","KTU","KTV","KTW","KTX","KTY","KUA","KUC","KUD",
  "KUE","KUF","KUG","KUH","KUK","KUL","KUM","KUN","KUO","KUP",
  "KUQ","KUR","KUS","KUT","KUU","KUV","KUX","KUY","KUZ","KVA",
  "KVB","KVC","KVD","KVE","KVG","KVK","KVL","KVM","KVO","KVR",
  "KVU","KVX","KWA","KWB","KWD","KWE","KWF","KWG","KWH","KWI",
  "KWJ","KWK","KWL","KWM","KWN","KWO","KWP","KWS","KWT","KWY",
  "KWZ","KXA","KXB","KXD","KXE","KXF","KXK","KXO","KXU","KYA",
  "KYB","KYD","KYE","KYF","KYI","KYK","KYO","KYP","KYS","KYT",
  "KYU","KYX","KYZ","KZB","KZC","KZD","KZF","KZG","KZI","KZN",
  "KZO","KZR","KZS","LAA","LAB","LAC","LAD","LAE","LAF","LAH",
  "LAI","LAJ","LAK","LAL","LAM","LAN","LAO","LAP","LAQ","LAR",
  "LAS","LAU","LAW","LAX","LAY","LAZ","LBA","LBB","LBC","LBD",
  "LBE","LBF","LBG","LBH","LBI","LBJ","LBK","LBL","LBM","LBN",
  "LBO","LBP","LBQ","LBR","LBS","LBT","LBU","LBV","LBW","LBX",
  "LBY","LBZ","LCA","LCB","LCC","LCD","LCE","LCF","LCG","LCH",
  "LCI","LCJ","LCK","LCL","LCM","LCN","LCO","LCP","LCQ","LCR",
  "LCS","LCT","LCX","LCY","LDA","LDB","LDC","LDE","LDG","LDH",
  "LDI","LDJ","LDK","LDM","LDN","LDO","LDS","LDU","LDV","LDW",
  "LDX","LDY","LDZ","LEA","LEB","LEC","LED","LEE","LEF","LEH",
  "LEI","LEJ","LEK","LEL","LEM","LEN","LEO","LEP","LEQ","LER",
  "LES","LET","LEU","LEV","LEW","LEX","LEY","LEZ","LFB","LFH",
  "LFI","LFK","LFM","LFN","LFO","LFP","LFQ","LFR","LFT","LFW",
  "LGA","LGB","LGC","LGD","LGE","LGF","LGG","LGH","LGI","LGK",
  "LGL","LGN","LGO","LGP","LGQ","LGR","LGS","LGT","LGU","LGW",
  "LGX","LGZ","LHA","LHE","LHG","LHI","LHK","LHN","LHR","LHS",
  "LHU","LHV","LHW","LIA","LIB","LIC","LID","LIE","LIF","LIG",
  "LIH","LII","LIJ","LIK","LIL","LIM","LIN","LIO","LIP","LIQ",
  "LIR","LIS","LIT","LIV","LIW","LIX","LIY","LIZ","LJA","LJG",
  "LJN","LJU","LKA","LKB","LKC","LKD","LKE","LKG","LKH","LKI",
  "LKK","LKL","LKM","LKN","LKO","LKP","LKR","LKU","LKV","LKW",
  "LKY","LKZ","LLA","LLB","LLC","LLE","LLF","LLG","LLH","LLI",
  "LLJ","LLK","LLL","LLM","LLN","LLO","LLS","LLT","LLU","LLV",
  "LLW","LLX","LLY","LMA","LMB","LMC","LMD","LME","LMH","LMI",
  "LML","LMM","LMN","LMO","LMP","LMQ","LMR","LMS","LMT","LMU",
  "LMV","LMX","LMY","LMZ","LNA","LNB","LNC","LND","LNE","LNF",
  "LNG","LNH","LNI","LNJ","LNK","LNL","LNM","LNN","LNO","LNP",
  "LNR","LNS","LNU","LNV","LNX","LNY","LNZ","LOA","LOB","LOC",
  "LOD","LOE","LOH","LOI","LOK","LOL","LOM","LOO","LOP","LOQ",
  "LOR","LOS","LOT","LOU","LOV","LOW","LOY","LOZ","LPA","LPB",
  "LPC","LPD","LPE","LPF","LPG","LPI","LPJ","LPK","LPL","LPM",
  "LPN","LPO","LPP","LPQ","LPS","LPT","LPU","LPX","LPY","LQK",
  "LQM","LQN","LRA","LRB","LRD","LRE","LRF","LRG","LRH","LRJ",
  "LRL","LRM","LRQ","LRR","LRS","LRT","LRU","LRV","LSA","LSB",
  "LSC","LSE","LSF","LSH","LSI","LSJ","LSK","LSL","LSM","LSN",
  "LSO","LSP","LSQ","LSR","LSS","LST","LSU","LSV","LSW","LSX",
  "LSY","LSZ","LTA","LTC","LTD","LTF","LTG","LTH","LTI","LTK",
  "LTL","LTM","LTN","LTO","LTP","LTQ","LTS","LTT","LTU","LTV",
  "LTW","LTX","LUA","LUB","LUC","LUD","LUE","LUF","LUG","LUH",
  "LUI","LUK","LUL","LUM","LUN","LUO","LUP","LUQ","LUR","LUT",
  "LUU","LUV","LUW","LUX","LUZ","LVA","LVD","LVI","LVK","LVL",
  "LVM","LVO","LVP","LVR","LVS","LWA","LWB","LWC","LWE","LWH",
  "LWI","LWK","LWL","LWM","LWN","LWO","LWR","LWS","LWT","LWV",
  "LWY","LXA","LXG","LXN","LXR","LXS","LXU","LXV","LYA","LYB",
  "LYC","LYE","LYG","LYH","LYI","LYK","LYM","LYN","LYO","LYP",
  "LYS","LYT","LYU","LYX","LZA","LZC","LZG","LZH","LZI","LZM",
  "LZN","LZO","LZR","LZU","LZY","MAA","MAB","MAC","MAD","MAE",
  "MAF","MAG","MAH","MAI","MAJ","MAK","MAM","MAN","MAO","MAP",
  "MAQ","MAR","MAS","MAT","MAU","MAV","MAW","MAX","MAY","MAZ",
  "MBA","MBB","MBC","MBD","MBE","MBF","MBG","MBH","MBI","MBJ",
  "MBK","MBL","MBM","MBN","MBO","MBP","MBQ","MBS","MBT","MBU",
  "MBV","MBW","MBX","MBY","MBZ","MCA","MCB","MCC","MCD","MCE",
  "MCF","MCG","MCH","MCI","MCJ","MCK","MCL","MCM","MCN","MCO",
  "MCP","MCS","MCT","MCU","MCV","MCW","MCX","MCY","MCZ","MDA",
  "MDB","MDC","MDD","MDE","MDF","MDG","MDH","MDI","MDJ","MDK",
  "MDL","MDM","MDN","MDO","MDP","MDQ","MDR","MDS","MDT","MDU",
  "MDW","MDX","MDY","MDZ","MEA","MEB","MEC","MED","MEE","MEF",
  "MEG","MEH","MEI","MEJ","MEK","MEL","MEM","MEN","MEO","MEP",
  "MEQ","MER","MES","MET","MEU","MEV","MEW","MEX","MEY","MEZ",
  "MFA","MFB","MFC","MFD","MFE","MFF","MFG","MFH","MFI","MFJ",
  "MFK","MFL","MFM","MFN","MFO","MFP","MFQ","MFR","MFS","MFU",
  "MFV","MFX","MFZ","MGA","MGB","MGC","MGD","MGE","MGF","MGH",
  "MGI","MGJ","MGK","MGL","MGM","MGN","MGP","MGQ","MGR","MGS",
  "MGT","MGU","MGV","MGW","MGX","MGY","MGZ","MHA","MHB","MHC",
  "MHD","MHE","MHF","MHG","MHH","MHI","MHK","MHL","MHM","MHN",
  "MHO","MHP","MHQ","MHR","MHS","MHT","MHU","MHV","MHW","MHX",
  "MHY","MHZ","MIA","MIB","MIC","MID","MIE","MIF","MIG","MIH",
  "MII","MIJ","MIK","MIM","MIN","MIO","MIP","MIQ","MIR","MIS",
  "MIT","MIU","MIV","MIW","MIX","MIY","MIZ","MJA","MJB","MJC",
  "MJD","MJE","MJF","MJG","MJI","MJJ","MJK","MJL","MJM","MJN",
  "MJO","MJP","MJQ","MJR","MJS","MJT","MJU","MJV","MJW","MJX",
  "MJY","MJZ","MKB","MKC","MKE","MKG","MKH","MKI","MKJ","MKK",
  "MKL","MKM","MKN","MKO","MKP","MKQ","MKR","MKS","MKT","MKU",
  "MKW","MKY","MKZ","MLA","MLB","MLC","MLD","MLE","MLF","MLG",
  "MLI","MLJ","MLK","MLL","MLM","MLN","MLO","MLP","MLQ","MLR",
  "MLS","MLT","MLU","MLV","MLW","MLX","MLY","MLZ","MMB","MMC",
  "MMD","MME","MMF","MMG","MMH","MMI","MMJ","MMK","MML","MMM",
  "MMN","MMO","MMP","MMQ","MMS","MMT","MMU","MMV","MMX","MMY",
  "MMZ","MNA","MNB","MNC","MND","MNE","MNF","MNG","MNH","MNI",
  "MNJ","MNK","MNL","MNM","MNN","MNO","MNP","MNQ","MNR","MNS",
  "MNT","MNU","MNV","MNW","MNX","MNY","MNZ","MOA","MOB","MOC",
  "MOD","MOE","MOF","MOG","MOH","MOI","MOJ","MOK","MOL","MOM",
  "MON","MOO","MOP","MOQ","MOR","MOS","MOT","MOU","MOV","MOX",
  "MOY","MOZ","MPA","MPB","MPC","MPD","MPF","MPG","MPH","MPI",
  "MPJ","MPK","MPL","MPM","MPN","MPO","MPP","MPR","MPS","MPT",
  "MPU","MPV","MPW","MPX","MPY","MPZ","MQA","MQB","MQC","MQD",
  "MQE","MQF","MQG","MQH","MQJ","MQK","MQL","MQM","MQO","MQP",
  "MQQ","MQR","MQS","MQT","MQU","MQV","MQW","MQX","MQY","MQZ",
  "MRA","MRB","MRC","MRD","MRE","MRF","MRG","MRH","MRI","MRK",
  "MRM","MRN","MRO","MRP","MRQ","MRR","MRS","MRT","MRU","MRV",
  "MRW","MRX","MRY","MRZ","MSA","MSB","MSC","MSE","MSF","MSG",
  "MSH","MSI","MSJ","MSK","MSL","MSM","MSN","MSO","MSP","MSQ",
  "MSR","MSS","MST","MSU","MSV","MSW","MSX","MSY","MSZ","MTA",
  "MTB","MTC","MTD","MTE","MTF","MTG","MTH","MTI","MTJ","MTK",
  "MTL","MTM","MTN","MTO","MTP","MTQ","MTR","MTS","MTT","MTU",
  "MTV","MTW","MTX","MTY","MTZ","MUA","MUB","MUC","MUD","MUE",
  "MUG","MUH","MUI","MUJ","MUK","MUL","MUM","MUN","MUO","MUP",
  "MUQ","MUR","MUS","MUT","MUU","MUW","MUX","MUY","MUZ","MVA",
  "MVB","MVC","MVD","MVE","MVF","MVK","MVL","MVM","MVN","MVO",
  "MVP","MVQ","MVR","MVS","MVT","MVU","MVV","MVW","MVX","MVY",
  "MVZ","MWA","MWB","MWC","MWD","MWE","MWF","MWG","MWH","MWI",
  "MWJ","MWK","MWL","MWM","MWN","MWO","MWQ","MWR","MWS","MWT",
  "MWU","MWV","MWX","MWY","MWZ","MXA","MXB","MXC","MXD","MXE",
  "MXF","MXH","MXI","MXJ","MXK","MXL","MXM","MXN","MXO","MXP",
  "MXQ","MXR","MXS","MXT","MXU","MXV","MXW","MXX","MXY","MXZ",
  "MYA","MYB","MYC","MYD","MYE","MYF","MYG","MYH","MYI","MYJ",
  "MYK","MYL","MYM","MYN","MYO","MYP","MYQ","MYR","MYS","MYT",
  "MYU","MYV","MYW","MYX","MYY","MYZ","MZA","MZB","MZC","MZD",
  "MZE","MZG","MZH","MZI","MZJ","MZK","MZL","MZM","MZN","MZO",
  "MZP","MZQ","MZR","MZS","MZT","MZU","MZV","MZW","MZY","MZZ",
  "NAA","NAC","NAD","NAE","NAF","NAG","NAH","NAI","NAJ","NAK",
  "NAL","NAM","NAN","NAO","NAP","NAQ","NAR","NAS","NAT","NAU",
  "NAV","NAW","NAY","NAZ","NBA","NBB","NBC","NBE","NBG","NBH",
  "NBJ","NBL","NBN","NBO","NBS","NBW","NBX","NCA","NCE","NCG",
  "NCH","NCI","NCJ","NCL","NCN","NCO","NCR","NCS","NCT","NCU",
  "NCY","NDA","NDB","NDC","NDD","NDE","NDF","NDG","NDI","NDJ",
  "NDK","NDL","NDM","NDN","NDR","NDS","NDU","NDY","NEC","NEG",
  "NEI","NEJ","NEK","NEL","NEN","NER","NEU","NEV","NEW","NFG",
  "NFL","NFR","NGA","NGB","NGD","NGE","NGF","NGI","NGK","NGL",
  "NGO","NGP","NGQ","NGS","NGU","NGW","NGX","NGZ","NHA","NHD",
  "NHF","NHK","NHT","NHV","NHX","NHZ","NIA","NIB","NIF","NIG",
  "NIK","NIM","NIN","NIO","NIP","NIQ","NIR","NIS","NIT","NIU",
  "NIX","NJA","NJC","NJF","NJJ","NJK","NKA","NKB","NKC","NKD",
  "NKG","NKI","NKL","NKM","NKN","NKO","NKP","NKT","NKU","NKW",
  "NKX","NKY","NLA","NLC","NLD","NLE","NLF","NLG","NLH","NLI",
  "NLK","NLL","NLN","NLO","NLP","NLS","NLT","NLU","NLV","NMA",
  "NMB","NMC","NME","NMF","NMG","NMI","NML","NMN","NMP","NMR",
  "NMS","NMT","NNA","NNB","NND","NNG","NNI","NNK","NNL","NNM",
  "NNR","NNT","NNU","NNX","NNY","NOA","NOB","NOC","NOD","NOG",
  "NOI","NOJ","NOK","NOM","NON","NOO","NOP","NOR","NOS","NOT",
  "NOU","NOV","NOZ","NPA","NPE","NPG","NPH","NPL","NPO","NPP",
  "NPR","NPT","NPU","NPY","NQA","NQI","NQL","NQN","NQT","NQU",
  "NQX","NQY","NQZ","NRA","NRB","NRD","NRE","NRG","NRI","NRK",
  "NRL","NRM","NRN","NRR","NRS","NRT","NRY","NSB","NSE","NSH",
  "NSI","NSK","NSL","NSM","NSN","NSO","NSQ","NSR","NST","NSV",
  "NSY","NTB","NTC","NTD","NTE","NTG","NTI","NTJ","NTL","NTN",
  "NTO","NTQ","NTR","NTT","NTU","NTX","NTY","NUA","NUB","NUD",
  "NUE","NUF","NUG","NUH","NUI","NUJ","NUK","NUL","NUM","NUP",
  "NUQ","NUR","NUS","NUU","NUW","NUX","NVA","NVD","NVI","NVK",
  "NVM","NVN","NVP","NVS","NVT","NVY","NWA","NWH","NWI","NWT",
  "NXX","NYA","NYE","NYG","NYI","NYK","NYM","NYN","NYO","NYR",
  "NYS","NYT","NYU","NYW","NZA","NZC","NZE","NZG","NZH","NZJ",
  "NZL","NZY","OAA","OAG","OAH","OAI","OAJ","OAK","OAL","OAM",
  "OAN","OAR","OAS","OAX","OAZ","OBC","OBD","OBE","OBF","OBI",
  "OBL","OBM","OBN","OBO","OBS","OBU","OBX","OBY","OCA","OCC",
  "OCE","OCF","OCH","OCJ","OCM","OCN","OCS","OCV","OCW","ODA",
  "ODB","ODC","ODD","ODE","ODH","ODJ","ODL","ODM","ODN","ODO",
  "ODR","ODS","ODT","ODW","ODY","OEA","OEC","OEL","OEM","OEO",
  "OER","OES","OFF","OFI","OFK","OFU","OGA","OGB","OGD","OGE",
  "OGG","OGL","OGM","OGN","OGO","OGR","OGS","OGU","OGX","OGZ",
  "OHA","OHB","OHD","OHE","OHH","OHI","OHO","OHR","OHS","OHT",
  "OIA","OIC","OIM","OIR","OIT","OJC","OJU","OKA","OKB","OKC",
  "OKD","OKE","OKF","OKG","OKI","OKJ","OKK","OKL","OKM","OKN",
  "OKO","OKP","OKQ","OKR","OKS","OKT","OKU","OKV","OKY","OLA",
  "OLB","OLC","OLD","OLE","OLF","OLG","OLH","OLI","OLJ","OLK",
  "OLL","OLM","OLN","OLO","OLP","OLQ","OLR","OLS","OLU","OLV",
  "OLX","OLY","OLZ","OMA","OMB","OMC","OMD","OME","OMF","OMG",
  "OMH","OMI","OMJ","OMK","OMM","OMN","OMO","OMR","OMS","OMY",
  "ONA","ONB","OND","ONG","ONH","ONI","ONJ","ONK","ONL","ONM",
  "ONO","ONP","ONQ","ONR","ONS","ONT","ONU","ONX","ONY","OOA",
  "OOD","OOK","OOL","OOM","OOR","OOT","OPA","OPB","OPF","OPI",
  "OPL","OPO","OPP","OPS","OPU","OPW","OQN","ORA","ORB","ORC",
  "ORD","ORE","ORF","ORG","ORH","ORI","ORJ","ORK","ORL","ORN",
  "ORO","ORP","ORR","ORT","ORU","ORV","ORW","ORX","ORY","ORZ",
  "OSB","OSC","OSD","OSE","OSF","OSG","OSH","OSI","OSJ","OSK",
  "OSL","OSM","OSN","OSO","OSP","OSR","OSS","OST","OSU","OSW",
  "OSX","OSY","OTC","OTD","OTG","OTH","OTI","OTJ","OTK","OTL",
  "OTM","OTN","OTO","OTP","OTQ","OTR","OTS","OTT","OTU","OTZ",
  "OUA","OUD","OUE","OUG","OUH","OUI","OUK","OUL","OUM","OUN",
  "OUR","OUS","OUT","OUZ","OVA","OVB","OVD","OVE","OVG","OVL",
  "OVR","OVS","OWA","OWB","OWD","OWK","OXB","OXC","OXD","OXF",
  "OXO","OXR","OXY","OYA","OYC","OYE","OYG","OYK","OYL","OYN",
  "OYO","OYP","OZA","OZC","OZG","OZH","OZP","OZR","OZZ","PAA",
  "PAB","PAC","PAD","PAE","PAF","PAG","PAH","PAJ","PAK","PAL",
  "PAM","PAN","PAO","PAP","PAQ","PAS","PAT","PAU","PAV","PAW",
  "PAX","PAY","PAZ","PBA","PBB","PBC","PBD","PBE","PBG","PBH",
  "PBI","PBJ","PBL","PBM","PBN","PBO","PBP","PBQ","PBR","PBT",
  "PBU","PBX","PBZ","PCA","PCB","PCC","PCD","PCF","PCG","PCH",
  "PCJ","PCL","PCM","PCN","PCO","PCP","PCQ","PCR","PCS","PCT",
  "PCU","PCV","PDA","PDB","PDC","PDD","PDE","PDF","PDG","PDI",
  "PDK","PDL","PDM","PDN","PDO","PDP","PDR","PDS","PDT","PDU",
  "PDV","PDX","PDZ","PEA","PEB","PEC","PED","PEE","PEF","PEG",
  "PEH","PEI","PEK","PEL","PEM","PEN","PEP","PEQ","PER","PES",
  "PET","PEU","PEV","PEW","PEX","PEY","PEZ","PFA","PFB","PFC",
  "PFJ","PFM","PFN","PFO","PFQ","PFR","PGA","PGB","PGC","PGD",
  "PGE","PGF","PGH","PGI","PGK","PGL","PGM","PGN","PGO","PGQ",
  "PGR","PGS","PGU","PGV","PGX","PGZ","PHA","PHB","PHC","PHD",
  "PHE","PHF","PHG","PHH","PHI","PHK","PHL","PHN","PHO","PHP",
  "PHQ","PHR","PHS","PHT","PHW","PHX","PHY","PIA","PIB","PIC",
  "PID","PIE","PIF","PIH","PIK","PIL","PIM","PIN","PIO","PIP",
  "PIQ","PIR","PIS","PIT","PIU","PIV","PIW","PIX","PIZ","PJA",
  "PJB","PJC","PJG","PJM","PKA","PKB","PKC","PKD","PKE","PKF",
  "PKG","PKH","PKJ","PKK","PKM","PKN","PKO","PKP","PKR","PKT",
  "PKU","PKV","PKW","PKX","PKY","PKZ","PLA","PLD","PLE","PLF",
  "PLH","PLJ","PLK","PLL","PLM","PLN","PLO","PLP","PLQ","PLR",
  "PLS","PLT","PLU","PLV","PLW","PLX","PLY","PLZ","PMA","PMB",
  "PMC","PMD","PMF","PMG","PMH","PMI","PMK","PML","PMN","PMO",
  "PMP","PMQ","PMR","PMS","PMT","PMV","PMW","PMY","PMZ","PNA",
  "PNB","PNC","PND","PNE","PNG","PNH","PNI","PNJ","PNK","PNL",
  "PNN","PNP","PNQ","PNR","PNS","PNT","PNU","PNV","PNX","PNY",
  "PNZ","POA","POB","POC","POD","POE","POF","POG","POH","POI",
  "POJ","POL","POM","PON","POO","POP","POR","POS","POT","POU",
  "POV","POW","POX","POY","POZ","PPA","PPB","PPC","PPE","PPF",
  "PPG","PPH","PPI","PPJ","PPK","PPL","PPM","PPN","PPP","PPQ",
  "PPR","PPS","PPT","PPU","PPV","PPW","PPX","PPY","PPZ","PQC",
  "PQD","PQI","PQM","PQQ","PQS","PQT","PRA","PRB","PRC","PRD",
  "PRE","PRG","PRH","PRI","PRK","PRM","PRN","PRO","PRP","PRQ",
  "PRR","PRS","PRU","PRV","PRW","PRX","PRY","PRZ","PSA","PSB",
  "PSC","PSD","PSE","PSF","PSG","PSH","PSI","PSJ","PSK","PSL",
  "PSM","PSN","PSO","PSP","PSQ","PSR","PSS","PSU","PSW","PSX",
  "PSY","PSZ","PTA","PTB","PTC","PTD","PTF","PTG","PTH","PTJ",
  "PTK","PTL","PTM","PTN","PTO","PTP","PTQ","PTS","PTT","PTU",
  "PTV","PTW","PTX","PTY","PTZ","PUA","PUB","PUC","PUD","PUE",
  "PUF","PUG","PUJ","PUK","PUL","PUN","PUP","PUQ","PUR","PUS",
  "PUT","PUU","PUV","PUW","PUX","PUY","PUZ","PVA","PVC","PVD",
  "PVE","PVF","PVG","PVH","PVI","PVK","PVL","PVO","PVR","PVS",
  "PVU","PVW","PWA","PWD","PWE","PWI","PWK","PWL","PWM","PWN",
  "PWO","PWQ","PWR","PWT","PWY","PXA","PXH","PXL","PXM","PXO",
  "PXR","PXU","PYA","PYB","PYC","PYE","PYG","PYH","PYJ","PYK",
  "PYL","PYM","PYN","PYO","PYR","PYS","PYT","PYV","PYY","PZA",
  "PZB","PZE","PZH","PZI","PZK","PZL","PZO","PZR","PZS","PZU",
  "PZY","QBC","QCH","QCJ","QCP","QCU","QCY","QDB","QDJ","QDV",
  "QDY","QEF","QFG","QFI","QFN","QFO","QFX","QGF","QGP","QGQ",
  "QGU","QGY","QHP","QHR","QHU","QHV","QIG","QIT","QJB","QJE",
  "QJH","QJI","QJP","QKX","QLA","QLD","QLF","QLG","QLP","QLR",
  "QLS","QLT","QMJ","QNC","QND","QNJ","QNS","QNV","QOQ","QOW",
  "QPA","QPD","QPG","QPS","QPW","QQT","QRA","QRC","QRF","QRM",
  "QRO","QRR","QRW","QRY","QSA","QSC","QSF","QSI","QSN","QSR",
  "QSX","QSZ","QUB","QUG","QUO","QUV","QUW","QUY","QXH","QYD",
  "RAA","RAB","RAC","RAD","RAE","RAF","RAG","RAH","RAI","RAJ",
  "RAK","RAL","RAM","RAN","RAO","RAP","RAQ","RAR","RAS","RAT",
  "RAV","RAW","RAX","RAZ","RBA","RBB","RBC","RBD","RBE","RBF",
  "RBG","RBI","RBJ","RBK","RBL","RBM","RBO","RBP","RBQ","RBR",
  "RBS","RBT","RBU","RBV","RBW","RBX","RBY","RBZ","RCA","RCB",
  "RCE","RCH","RCK","RCL","RCM","RCO","RCQ","RCR","RCS","RCU",
  "RCY","RDA","RDB","RDC","RDD","RDE","RDG","RDL","RDM","RDN",
  "RDO","RDP","RDR","RDS","RDT","RDU","RDV","RDZ","REA","REB",
  "REC","RED","REE","REG","REI","REL","REN","REO","REP","REQ",
  "RER","RES","RET","REU","REX","REY","REZ","RFA","RFD","RFG",
  "RFK","RFN","RFP","RFR","RFS","RGA","RGH","RGI","RGK","RGL",
  "RGN","RGO","RGR","RGS","RGT","RHA","RHD","RHE","RHG","RHI",
  "RHL","RHN","RHO","RHP","RHT","RHV","RIA","RIB","RIC","RID",
  "RIE","RIF","RIG","RIH","RIJ","RIL","RIM","RIN","RIR","RIS",
  "RIV","RIW","RIX","RIY","RIZ","RJA","RJB","RJH","RJI","RJK",
  "RJL","RJM","RJN","RKA","RKD","RKE","RKH","RKI","RKO","RKP",
  "RKR","RKS","RKT","RKU","RKV","RKW","RKY","RKZ","RLA","RLD",
  "RLG","RLK","RLO","RLP","RLR","RLT","RMA","RMB","RMD","RME",
  "RMF","RMG","RMI","RMK","RML","RMN","RMO","RMP","RMQ","RMS",
  "RMT","RMU","RMY","RMZ","RNA","RNB","RNC","RND","RNE","RNH",
  "RNI","RNJ","RNL","RNM","RNN","RNO","RNP","RNS","RNT","RNU",
  "RNZ","ROA","ROB","ROC","ROD","ROF","ROG","ROH","ROI","ROK",
  "ROL","RON","ROO","ROP","ROR","ROS","ROT","ROU","ROV","ROW",
  "ROX","ROY","ROZ","RPA","RPB","RPM","RPN","RPR","RPU","RPV",
  "RPX","RQA","RQO","RQW","RQY","RRE","RRG","RRJ","RRK","RRL",
  "RRM","RRR","RRS","RRT","RRV","RSA","RSB","RSD","RSE","RSH",
  "RSI","RSJ","RSK","RSL","RSN","RSS","RST","RSU","RSW","RSX",
  "RTA","RTB","RTC","RTE","RTG","RTI","RTL","RTM","RTN","RTO",
  "RTP","RTS","RTU","RTW","RTY","RUA","RUD","RUE","RUF","RUG",
  "RUH","RUI","RUK","RUL","RUM","RUN","RUP","RUR","RUS","RUT",
  "RUU","RUV","RUY","RVA","RVC","RVD","RVE","RVN","RVO","RVR",
  "RVS","RVT","RVV","RVY","RWF","RWI","RWL","RWN","RXA","RXE",
  "RXS","RYB","RYK","RYL","RYN","RYO","RZA","RZE","RZH","RZP",
  "RZR","RZS","RZV","SAA","SAB","SAC","SAD","SAE","SAF","SAG",
  "SAH","SAI","SAK","SAL","SAM","SAN","SAP","SAQ","SAR","SAS",
  "SAT","SAU","SAV","SAW","SAX","SAY","SAZ","SBA","SBB","SBC",
  "SBD","SBE","SBF","SBG","SBH","SBI","SBJ","SBK","SBL","SBM",
  "SBN","SBO","SBP","SBQ","SBR","SBS","SBT","SBU","SBV","SBW",
  "SBX","SBY","SBZ","SCA","SCB","SCC","SCD","SCE","SCF","SCG",
  "SCH","SCI","SCK","SCL","SCM","SCN","SCO","SCQ","SCR","SCS",
  "SCT","SCU","SCV","SCW","SCX","SCY","SCZ","SDB","SDC","SDD",
  "SDE","SDF","SDG","SDI","SDJ","SDK","SDL","SDM","SDN","SDP",
  "SDQ","SDR","SDS","SDT","SDU","SDV","SDW","SDX","SDY","SEA",
  "SEB","SEE","SEF","SEG","SEH","SEK","SEM","SEN","SEO","SEP",
  "SEQ","SER","SES","SET","SEU","SEW","SEY","SEZ","SFA","SFB",
  "SFC","SFD","SFE","SFF","SFG","SFH","SFJ","SFK","SFL","SFM",
  "SFN","SFO","SFQ","SFS","SFT","SFU","SFV","SFX","SFZ","SGA",
  "SGC","SGD","SGE","SGF","SGG","SGH","SGI","SGK","SGL","SGM",
  "SGN","SGO","SGP","SGQ","SGR","SGT","SGU","SGV","SGW","SGX",
  "SGY","SGZ","SHA","SHB","SHC","SHD","SHE","SHF","SHG","SHH",
  "SHI","SHJ","SHK","SHL","SHM","SHN","SHO","SHP","SHQ","SHR",
  "SHS","SHT","SHU","SHV","SHW","SHX","SHY","SHZ","SIA","SIB",
  "SIC","SID","SIF","SIG","SIH","SIJ","SIK","SIL","SIM","SIN",
  "SIO","SIP","SIQ","SIR","SIS","SIT","SIU","SIV","SIW","SIX",
  "SIY","SIZ","SJA","SJB","SJC","SJD","SJE","SJF","SJH","SJI",
  "SJJ","SJK","SJL","SJN","SJO","SJP","SJQ","SJR","SJS","SJT",
  "SJU","SJV","SJW","SJX","SJY","SJZ","SKA","SKB","SKC","SKD",
  "SKE","SKF","SKG","SKH","SKJ","SKK","SKM","SKN","SKO","SKP",
  "SKQ","SKR","SKS","SKT","SKU","SKV","SKW","SKX","SKY","SKZ",
  "SLA","SLB","SLC","SLD","SLE","SLF","SLG","SLH","SLI","SLJ",
  "SLK","SLL","SLM","SLN","SLO","SLP","SLQ","SLR","SLT","SLU",
  "SLV","SLW","SLX","SLY","SLZ","SMA","SMB","SMD","SME","SMF",
  "SMH","SMI","SMJ","SMK","SML","SMM","SMN","SMO","SMP","SMQ",
  "SMR","SMS","SMT","SMU","SMV","SMW","SMX","SMY","SMZ","SNA",
  "SNB","SNC","SNE","SNF","SNG","SNH","SNI","SNJ","SNK","SNL",
  "SNM","SNN","SNO","SNP","SNQ","SNR","SNS","SNT","SNU","SNV",
  "SNW","SNX","SNY","SNZ","SOA","SOB","SOC","SOD","SOE","SOF",
  "SOG","SOH","SOI","SOJ","SOK","SOL","SOM","SON","SOO","SOP",
  "SOQ","SOR","SOT","SOU","SOV","SOW","SOX","SOY","SOZ","SPA",
  "SPB","SPC","SPD","SPE","SPF","SPG","SPH","SPI","SPJ","SPM",
  "SPN","SPP","SPQ","SPR","SPS","SPT","SPU","SPV","SPW","SPX",
  "SPY","SPZ","SQA","SQB","SQC","SQD","SQE","SQF","SQG","SQH",
  "SQI","SQJ","SQK","SQL","SQM","SQN","SQO","SQQ","SQR","SQS",
  "SQT","SQU","SQV","SQW","SQX","SQY","SQZ","SRA","SRB","SRC",
  "SRD","SRE","SRG","SRH","SRI","SRJ","SRK","SRL","SRM","SRN",
  "SRO","SRP","SRQ","SRR","SRS","SRT","SRU","SRV","SRW","SRX",
  "SRY","SRZ","SSA","SSB","SSC","SSD","SSE","SSF","SSG","SSH",
  "SSI","SSJ","SSK","SSL","SSN","SSO","SSP","SSQ","SSR","SSS",
  "SST","SSW","SSX","SSY","SSZ","STA","STB","STC","STD","STE",
  "STF","STG","STH","STI","STJ","STK","STL","STM","STN","STP",
  "STQ","STR","STS","STT","STU","STV","STW","STX","STY","STZ",
  "SUA","SUB","SUD","SUE","SUF","SUG","SUI","SUJ","SUK","SUL",
  "SUM","SUN","SUO","SUP","SUQ","SUR","SUS","SUT","SUU","SUV",
  "SUW","SUX","SUY","SVA","SVB","SVC","SVD","SVE","SVF","SVG",
  "SVH","SVI","SVJ","SVK","SVL","SVN","SVO","SVP","SVQ","SVR",
  "SVS","SVT","SVU","SVV","SVW","SVX","SVZ","SWA","SWB","SWC",
  "SWD","SWE","SWF","SWG","SWH","SWJ","SWL","SWN","SWO","SWP",
  "SWQ","SWR","SWS","SWT","SWU","SWV","SWW","SWX","SWY","SXA",
  "SXB","SXE","SXF","SXG","SXH","SXI","SXJ","SXK","SXL","SXM",
  "SXN","SXO","SXP","SXQ","SXR","SXS","SXT","SXU","SXV","SXW",
  "SXX","SXY","SXZ","SYA","SYB","SYC","SYD","SYE","SYF","SYH",
  "SYI","SYJ","SYK","SYL","SYM","SYN","SYO","SYP","SYQ","SYR",
  "SYS","SYT","SYU","SYV","SYW","SYX","SYY","SYZ","SZA","SZB",
  "SZE","SZF","SZG","SZH","SZI","SZJ","SZK","SZL","SZM","SZN",
  "SZP","SZR","SZS","SZT","SZV","SZW","SZX","SZY","SZZ","TAB",
  "TAC","TAD","TAE","TAF","TAG","TAH","TAI","TAJ","TAK","TAL",
  "TAM","TAN","TAO","TAP","TAQ","TAR","TAS","TAT","TAU","TAW",
  "TAX","TAY","TAZ","TBB","TBC","TBD","TBE","TBF","TBG","TBH",
  "TBI","TBJ","TBK","TBL","TBM","TBN","TBO","TBP","TBQ","TBR",
  "TBS","TBT","TBU","TBV","TBW","TBX","TBY","TBZ","TCA","TCB",
  "TCC","TCD","TCE","TCF","TCG","TCH","TCJ","TCK","TCL","TCM",
  "TCN","TCO","TCP","TCQ","TCR","TCS","TCT","TCU","TCW","TCX",
  "TCY","TCZ","TDA","TDB","TDD","TDG","TDJ","TDK","TDL","TDN",
  "TDO","TDP","TDR","TDS","TDT","TDV","TDW","TDX","TDZ","TEA",
  "TEB","TEC","TED","TEE","TEF","TEG","TEH","TEI","TEK","TEL",
  "TEM","TEN","TEO","TEP","TEQ","TER","TES","TET","TEU","TEV",
  "TEX","TEY","TEZ","TFB","TFF","TFI","TFL","TFM","TFN","TFS",
  "TFT","TFU","TFY","TGA","TGB","TGC","TGD","TGG","TGH","TGI",
  "TGJ","TGK","TGL","TGM","TGN","TGO","TGP","TGQ","TGR","TGS",
  "TGT","TGU","TGZ","THA","THB","THC","THD","THE","THF","THG",
  "THI","THK","THL","THM","THN","THO","THP","THQ","THR","THS",
  "THT","THU","THV","THW","THX","THY","THZ","TIA","TIB","TIC",
  "TID","TIE","TIF","TIH","TII","TIJ","TIK","TIL","TIM","TIN",
  "TIO","TIP","TIQ","TIR","TIU","TIV","TIW","TIX","TIY","TIZ",
  "TJA","TJB","TJC","TJG","TJH","TJI","TJK","TJL","TJM","TJN",
  "TJQ","TJS","TJU","TJV","TKA","TKB","TKC","TKD","TKE","TKF",
  "TKG","TKH","TKI","TKJ","TKK","TKL","TKM","TKN","TKO","TKP",
  "TKQ","TKR","TKS","TKT","TKU","TKV","TKW","TKX","TKY","TKZ",
  "TLA","TLB","TLC","TLD","TLE","TLF","TLG","TLH","TLI","TLJ",
  "TLK","TLL","TLM","TLN","TLO","TLP","TLQ","TLR","TLS","TLT",
  "TLU","TLV","TLW","TLX","TLY","TLZ","TMA","TMB","TMC","TMD",
  "TME","TMF","TMG","TMH","TMI","TMJ","TML","TMM","TMN","TMO",
  "TMP","TMQ","TMR","TMS","TMT","TMU","TMW","TMX","TMY","TMZ",
  "TNA","TNB","TNC","TND","TNE","TNF","TNG","TNH","TNI","TNJ",
  "TNK","TNL","TNM","TNN","TNO","TNP","TNQ","TNR","TNS","TNT",
  "TNU","TNV","TNW","TNX","TNZ","TOA","TOB","TOC","TOD","TOE",
  "TOF","TOG","TOH","TOI","TOJ","TOK","TOL","TOM","TON","TOO",
  "TOP","TOQ","TOR","TOS","TOT","TOU","TOV","TOW","TOX","TOY",
  "TOZ","TPA","TPC","TPE","TPF","TPG","TPH","TPI","TPJ","TPK",
  "TPL","TPN","TPP","TPQ","TPR","TPS","TPT","TPU","TPX","TQA",
  "TQD","TQI","TQL","TQN","TQO","TQP","TQQ","TQR","TQS","TRA",
  "TRB","TRC","TRD","TRE","TRG","TRH","TRI","TRJ","TRK","TRL",
  "TRM","TRN","TRO","TRQ","TRR","TRS","TRT","TRU","TRV","TRW",
  "TRX","TRY","TRZ","TSA","TSB","TSC","TSD","TSE","TSF","TSG",
  "TSH","TSI","TSJ","TSL","TSM","TSN","TSP","TSQ","TSR","TSS",
  "TST","TSU","TSV","TSW","TSX","TSY","TSZ","TTA","TTB","TTC",
  "TTD","TTE","TTG","TTH","TTI","TTJ","TTL","TTM","TTN","TTO",
  "TTQ","TTR","TTS","TTT","TTU","TTW","TTX","TUA","TUB","TUC",
  "TUD","TUF","TUG","TUH","TUI","TUJ","TUK","TUL","TUM","TUN",
  "TUO","TUP","TUQ","TUR","TUS","TUU","TUV","TUW","TUX","TUY",
  "TVA","TVC","TVF","TVI","TVL","TVS","TVU","TVY","TWA","TWB",
  "TWC","TWD","TWE","TWF","TWH","TWP","TWT","TWU","TWY","TWZ",
  "TXC","TXE","TXF","TXG","TXK","TXL","TXM","TXN","TXR","TXU",
  "TYA","TYB","TYC","TYD","TYE","TYF","TYG","TYL","TYM","TYN",
  "TYP","TYR","TYS","TYT","TYZ","TZA","TZC","TZL","TZM","TZN",
  "TZO","TZR","TZX","UAB","UAC","UAE","UAH","UAI","UAK","UAL",
  "UAM","UAP","UAQ","UAR","UAS","UAX","UBA","UBB","UBI","UBJ",
  "UBN","UBP","UBS","UBT","UBU","UCB","UCC","UCE","UCK","UCN",
  "UCT","UCY","UCZ","UDA","UDD","UDE","UDI","UDJ","UDR","UEE",
  "UEL","UEN","UEO","UES","UET","UFA","UGA","UGB","UGC","UGI",
  "UGL","UGN","UGO","UGS","UGT","UGU","UHE","UHS","UIB","UIH",
  "UII","UIK","UIL","UIN","UIO","UIP","UIR","UIT","UJE","UJU",
  "UKA","UKB","UKE","UKG","UKH","UKI","UKK","UKN","UKR","UKS",
  "UKT","UKU","UKX","ULA","ULB","ULD","ULE","ULG","ULH","ULI",
  "ULK","ULM","ULN","ULO","ULP","ULQ","ULS","ULU","ULV","ULX",
  "ULY","ULZ","UMA","UMB","UMC","UMD","UME","UMI","UMM","UMR",
  "UMS","UMT","UMU","UMY","UMZ","UNA","UNC","UND","UNE","UNG",
  "UNI","UNK","UNN","UNR","UNT","UNU","UOA","UOL","UOS","UOX",
  "UPB","UPG","UPL","UPN","UPP","UPR","URA","URC","URD","URE",
  "URG","URI","URJ","URM","URN","URO","URR","URS","URT","URU",
  "URY","URZ","USA","USH","USI","USJ","USK","USL","USM","USN",
  "USQ","USR","USS","UST","USU","UTA","UTB","UTC","UTD","UTE",
  "UTG","UTH","UTI","UTK","UTM","UTN","UTO","UTP","UTS","UTT",
  "UTU","UTW","UUA","UUD","UUK","UUN","UUS","UUU","UVA","UVE",
  "UVF","UVI","UVL","UVO","UWA","UYL","UYN","UYU","UZC","UZM",
  "UZR","UZU","VAA","VAB","VAC","VAD","VAF","VAG","VAH","VAI",
  "VAK","VAL","VAM","VAN","VAO","VAP","VAQ","VAR","VAS","VAT",
  "VAV","VBA","VBC","VBG","VBP","VBS","VBV","VBY","VCA","VCC",
  "VCD","VCE","VCF","VCH","VCL","VCP","VCR","VCS","VCT","VCV",
  "VDA","VDB","VDC","VDE","VDH","VDI","VDM","VDO","VDP","VDR",
  "VDS","VDY","VDZ","VEE","VEG","VEL","VEO","VER","VEV","VEX",
  "VEY","VFA","VGA","VGD","VGO","VGS","VGT","VGZ","VHC","VHM",
  "VHN","VHV","VHY","VHZ","VIA","VIC","VIE","VIG","VIH","VII",
  "VIJ","VIL","VIN","VIP","VIQ","VIR","VIS","VIT","VIU","VIV",
  "VIX","VIY","VJB","VJI","VJQ","VKG","VKO","VKS","VKT","VKV",
  "VLA","VLC","VLD","VLE","VLG","VLI","VLK","VLL","VLM","VLN",
  "VLO","VLP","VLR","VLS","VLU","VLV","VLY","VME","VMI","VMU",
  "VNA","VNC","VND","VNE","VNO","VNR","VNS","VNT","VNX","VNY",
  "VOD","VOG","VOH","VOI","VOK","VOL","VOT","VOZ","VPE","VPG",
  "VPN","VPS","VPY","VPZ","VQQ","VQS","VRA","VRB","VRC","VRE",
  "VRI","VRK","VRL","VRN","VRO","VRS","VRU","VRY","VRZ","VSA",
  "VSE","VSF","VSG","VST","VSV","VTB","VTE","VTF","VTG","VTM",
  "VTN","VTU","VTZ","VUP","VUS","VUU","VVB","VVC","VVI","VVK",
  "VVN","VVO","VVZ","VXC","VXE","VXO","VYD","VYI","VYS","WAA",
  "WAD","WAE","WAF","WAG","WAH","WAI","WAJ","WAK","WAL","WAM",
  "WAO","WAP","WAQ","WAR","WAT","WAU","WAV","WAW","WAX","WAY",
  "WAZ","WBA","WBB","WBC","WBD","WBE","WBG","WBK","WBM","WBO",
  "WBQ","WBR","WBU","WBW","WCA","WCD","WCH","WCR","WDB","WDG",
  "WDH","WDI","WDN","WDR","WDS","WEA","WED","WEF","WEH","WEI",
  "WEL","WEP","WET","WEW","WFB","WFI","WFK","WFR","WGA","WGB",
  "WGC","WGE","WGN","WGO","WGP","WGT","WHA","WHB","WHD","WHF",
  "WHK","WHL","WHN","WHO","WHP","WHT","WHU","WIB","WIC","WIE",
  "WIK","WIL","WIN","WIO","WIR","WIT","WIU","WJA","WJF","WJR",
  "WJU","WKA","WKB","WKF","WKI","WKJ","WKK","WKL","WKN","WKR",
  "WLA","WLC","WLD","WLE","WLG","WLH","WLK","WLL","WLO","WLP",
  "WLR","WLS","WLU","WLW","WMA","WMB","WMC","WMD","WME","WMH",
  "WMI","WMK","WML","WMN","WMO","WMP","WMR","WMT","WMX","WNA",
  "WND","WNH","WNI","WNN","WNP","WNR","WNS","WNU","WNZ","WOA",
  "WOE","WOK","WOL","WON","WOS","WOT","WOW","WPA","WPB","WPC",
  "WPK","WPL","WPM","WPO","WPR","WPU","WRA","WRB","WRE","WRG",
  "WRH","WRI","WRL","WRN","WRO","WRT","WRW","WRY","WRZ","WSA",
  "WSB","WSD","WSF","WSG","WSH","WSK","WSM","WSN","WSO","WSP",
  "WSR","WST","WSU","WSX","WSY","WSZ","WTA","WTB","WTD","WTE",
  "WTK","WTL","WTN","WTO","WTP","WTR","WTS","WTT","WTZ","WUA",
  "WUD","WUG","WUH","WUI","WUM","WUN","WUS","WUT","WUU","WUV",
  "WUX","WUZ","WVB","WVI","WVK","WVL","WVN","WWA","WWD","WWI",
  "WWK","WWP","WWR","WWT","WWY","WXN","WYA","WYB","WYE","WYN",
  "WYS","WZA","WZQ","XAB","XAI","XAL","XAP","XAR","XAU","XBB",
  "XBE","XBG","XBJ","XBN","XBO","XBR","XCH","XCL","XCM","XCO",
  "XCR","XCZ","XDE","XDJ","XEN","XEQ","XES","XFN","XFW","XGA",
  "XGG","XGN","XGR","XIC","XIE","XIG","XIJ","XIL","XIN","XIQ",
  "XIY","XJD","XJM","XKA","XKH","XKS","XKY","XLB","XLS","XLU",
  "XMA","XMC","XMD","XME","XMG","XMH","XMI","XML","XMN","XMP",
  "XMS","XMW","XMY","XNA","XNH","XNN","XNT","XNU","XOG","XPA",
  "XPK","XPL","XPP","XPR","XQC","XQP","XQU","XRH","XRQ","XRR",
  "XRY","XSB","XSC","XSD","XSE","XSI","XSO","XSP","XTG","XTL",
  "XTO","XTR","XUZ","XVS","XWA","XXN","XXX","XYA","XYE","XYR",
  "XZA","XZM","YAA","YAB","YAC","YAE","YAG","YAH","YAI","YAJ",
  "YAK","YAL","YAM","YAN","YAO","YAP","YAQ","YAR","YAS","YAT",
  "YAU","YAV","YAX","YAY","YAZ","YBA","YBB","YBC","YBE","YBF",
  "YBG","YBH","YBI","YBJ","YBK","YBL","YBO","YBP","YBQ","YBR",
  "YBS","YBT","YBV","YBW","YBX","YBY","YCA","YCB","YCC","YCD",
  "YCE","YCF","YCG","YCH","YCK","YCL","YCM","YCN","YCO","YCQ",
  "YCR","YCS","YCT","YCU","YCW","YCY","YCZ","YDA","YDB","YDC",
  "YDF","YDG","YDJ","YDL","YDN","YDO","YDP","YDQ","YDT","YDU",
  "YDV","YDW","YEB","YEC","YEG","YEH","YEI","YEK","YEL","YEM",
  "YEN","YEO","YEQ","YER","YES","YET","YEU","YEV","YEY","YFA",
  "YFB","YFC","YFE","YFG","YFH","YFI","YFJ","YFL","YFO","YFR",
  "YFS","YFX","YGA","YGB","YGE","YGG","YGH","YGJ","YGK","YGL",
  "YGM","YGN","YGO","YGP","YGQ","YGR","YGT","YGV","YGW","YGX",
  "YGZ","YHA","YHB","YHC","YHD","YHE","YHF","YHG","YHH","YHI",
  "YHJ","YHK","YHM","YHN","YHO","YHP","YHR","YHS","YHT","YHU",
  "YHY","YHZ","YIA","YIB","YIC","YIE","YIF","YIG","YIH","YIK",
  "YIN","YIO","YIP","YIV","YIW","YJA","YJF","YJN","YJP","YJS",
  "YJT","YKA","YKC","YKD","YKE","YKF","YKG","YKH","YKJ","YKK",
  "YKL","YKM","YKN","YKO","YKQ","YKS","YKT","YKU","YKX","YKY",
  "YKZ","YLB","YLC","YLD","YLE","YLG","YLH","YLI","YLJ","YLK",
  "YLL","YLP","YLQ","YLR","YLS","YLT","YLV","YLW","YLX","YLY",
  "YMA","YMB","YME","YMF","YMG","YMH","YMJ","YMK","YML","YMM",
  "YMN","YMO","YMP","YMS","YMT","YMU","YMV","YMW","YMX","YNA",
  "YNB","YNC","YND","YNE","YNG","YNH","YNJ","YNL","YNM","YNO",
  "YNP","YNS","YNT","YNX","YNY","YNZ","YOA","YOC","YOD","YOE",
  "YOG","YOH","YOI","YOJ","YOL","YON","YOO","YOP","YOS","YOW",
  "YPA","YPB","YPC","YPD","YPE","YPG","YPH","YPJ","YPL","YPM",
  "YPN","YPO","YPQ","YPR","YPS","YPT","YPW","YPX","YPY","YPZ",
  "YQA","YQB","YQC","YQD","YQF","YQG","YQH","YQI","YQJ","YQK",
  "YQL","YQM","YQN","YQQ","YQR","YQS","YQT","YQU","YQV","YQW",
  "YQX","YQY","YQZ","YRA","YRB","YRC","YRD","YRF","YRG","YRI",
  "YRJ","YRL","YRM","YRN","YRO","YRQ","YRR","YRS","YRT","YRV",
  "YSA","YSB","YSC","YSD","YSE","YSF","YSG","YSH","YSI","YSJ",
  "YSK","YSL","YSM","YSN","YSO","YSP","YSQ","YSR","YST","YSU",
  "YSV","YSX","YSY","YTA","YTB","YTD","YTE","YTF","YTG","YTH",
  "YTL","YTM","YTP","YTQ","YTR","YTS","YTT","YTW","YTY","YTZ",
  "YUA","YUB","YUD","YUE","YUK","YUL","YUM","YUS","YUT","YUX",
  "YUY","YVA","YVB","YVC","YVD","YVE","YVG","YVM","YVO","YVP",
  "YVQ","YVR","YVT","YVV","YVZ","YWA","YWB","YWG","YWH","YWJ",
  "YWK","YWL","YWM","YWP","YWQ","YWR","YWS","YWY","YXC","YXD",
  "YXE","YXH","YXJ","YXK","YXL","YXN","YXP","YXQ","YXR","YXS",
  "YXT","YXU","YXX","YXY","YXZ","YYA","YYB","YYC","YYD","YYE",
  "YYF","YYG","YYH","YYJ","YYL","YYM","YYN","YYQ","YYR","YYT",
  "YYU","YYW","YYY","YYZ","YZA","YZD","YZE","YZF","YZG","YZH",
  "YZP","YZR","YZS","YZT","YZU","YZV","YZW","YZX","YZY","YZZ",
  "ZAC","ZAD","ZAG","ZAH","ZAJ","ZAL","ZAM","ZAO","ZAR","ZAT",
  "ZAZ","ZBE","ZBF","ZBL","ZBM","ZBO","ZBR","ZBY","ZCL","ZCN",
  "ZCO","ZDM","ZDY","ZEC","ZEG","ZEL","ZEM","ZEN","ZER","ZFA",
  "ZFD","ZFL","ZFM","ZFN","ZFU","ZFW","ZGF","ZGI","ZGL","ZGM",
  "ZGN","ZGR","ZGS","ZGU","ZHA","ZHI","ZHM","ZHP","ZHY","ZIA",
  "ZIC","ZIG","ZIH","ZIN","ZIS","ZIX","ZIZ","ZJG","ZJI","ZJN",
  "ZKB","ZKE","ZKG","ZKL","ZKP","ZLO","ZLR","ZLT","ZLX","ZMD",
  "ZMG","ZMH","ZMM","ZMT","ZNA","ZNC","ZND","ZNE","ZNF","ZNU",
  "ZNZ","ZOE","ZOF","ZOS","ZPB","ZPC","ZPH","ZPO","ZQL","ZQN",
  "ZQS","ZQW","ZQZ","ZRH","ZRI","ZRJ","ZRM","ZSA","ZSE","ZSJ",
  "ZSS","ZST","ZSW","ZTA","ZTB","ZTH","ZTM","ZTR","ZTS","ZTU",
  "ZUC","ZUD","ZUH","ZUL","ZUM","ZVA","ZVG","ZVK","ZWA","ZWL",
  "ZXT","ZYI","ZYL","ZZE","ZZO","ZZU","ZZV"
];

// Ensure all answer codes are valid guesses
for (const a of ANSWERS) {
  if (!VALID_GUESSES.includes(a.code)) {
    VALID_GUESSES.push(a.code);
  }
}

export { ANSWERS, VALID_GUESSES };
